balancer/frontend-monorepo

packages/lib/shared/components/tooltips/apr-tooltip/AddLiquidityAprTooltip.tsx, packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx, packages/lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx, packages/lib/shared/components/tooltips/apr-tooltip/StakeAprTooltip.tsx, packages/lib/shared/hooks/useAprTooltip.ts
fixes #62 
when there are no surplus apr items show LVR as 0% for cow amm pools
=> fix: show 0% when there are no surplus apr items

packages/lib/modules/swap/SwapProvider.tsx
We had this bug: 
1. Go to swaps page and select `swap/gnosis/USDC/COW`
2. Manually update the url to `swap/gnosis/xDAI/COW` and hit ENTER
3. Bug: the tokenIn remains USDC when it should be xDAI
The reason is that the functions that udpate `swapStateVar` were using `swapState` without making sure that it had the most recent updated value, causing different issues when performing consecutive updates like in:
``` ts
setInitialChain(chain)
setInitialTokenIn(tokenIn)
setInitialTokenOut(tokenOut)
setInitialAmounts(amountIn, amountOut)
```
The solution is enforcing that `swapState` has the most last updated value with  `const swapState = swapStateVar()` before updating it again.
=> fix: use fresh swapState when updaring swapStateVar

apps/frontend-v3/.gitignore, apps/frontend-v3/app/(marketing)/build/v3/page.tsx
the top level page for /build/v3 was missing because `build/` was still in the app's `.gitignore`
=> fix: add build v3 page

.vscode/settings.json, packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableHeader.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx, packages/lib/modules/pool/pool.types.ts, packages/lib/shared/components/badges/BalBadge.tsx, packages/lib/shared/components/icons/logos/CowIcon.tsx
Updates type column to 'Details' and adds protocol version filter to filters popover. v3 filter option only visible on dev and staging envs.
=> feat: Pool list updates for v3

packages/lib/modules/pool/alerts/usePoolAlerts.tsx, packages/lib/modules/pool/pool.helpers.ts
- Avoid pool alerts in sepolia pools
- Avoid blocking add liquidity in sepolia pools
- Only check unsupported tokens for v2 pools
Example of pool that was blocked but it's not anymore:
https://mono-test-v3-mkgddj74u-balancer.vercel.app/pools/sepolia/v3/0x797c69b235cb047c9331d39c96f30f76dce6444d/add-liquidity
=> feat: unblock sepolia pools

apps/beets-frontend-v3/app/layout.tsx, apps/beets-frontend-v3/lib/services/chakra/ThemeProvider.tsx, apps/beets-frontend-v3/lib/services/chakra/themes/beets/beets.theme.ts, apps/beets-frontend-v3/lib/services/chakra/themes/beets/colors.ts, apps/frontend-v3/app/layout.tsx, apps/frontend-v3/lib/services/chakra/ThemeProvider.tsx, apps/frontend-v3/lib/services/chakra/themes/bal/bal.theme.ts, apps/frontend-v3/lib/services/chakra/themes/bal/colors.ts, apps/frontend-v3/lib/services/chakra/themes/cow/colors.ts, apps/frontend-v3/lib/services/chakra/themes/cow/cow.theme.ts, apps/frontend-v3/lib/services/chakra/themes/cow/tokens.ts, apps/frontend-v3/package.json, packages/lib/modules/transactions/transaction-steps/useSignPermitStep.tsx, packages/lib/package.json, packages/lib/shared/components/site/providers.tsx, pnpm-lock.yaml
suggestion to put the app specific themes back in the apps and keep the base theme in the lib package
this removes a dependency of `getProjectConfig`
=> chore: separate themes for apps

packages/lib/modules/swap/usePermit2SwapStep.tsx, packages/lib/modules/transactions/transaction-steps/useSignPermit2Step.tsx
Fixes wrap swaps. For example ETH to WETH.
The rules of react hooks make it difficult to do a clause guard return when `isPermit2` is false so we had to add explicit code to avoid an error when `queryData?.queryOutput` is undefined. 
Can be tested here: 
https://mono-test-v3-git-fix-wrappingswap-balancer.vercel.app/swap/ethereum/ETH/WETH/0.0001
=> fix: Avoid permit2 step for wrapping swap

packages/lib/modules/price-impact/price-impact.utils.ts, packages/lib/modules/swap/handlers/DefaultSwap.handler.integration.spec.tsx
SDK team: 
There are a few different errors that can be the cause depending on the edge case really.
Can you not catch any errors on the FE and display the generic error but we keep the more specific SDK error and pass it to Sentry to help us try to debug?
**If there is a price impact error but no query error**:
- show user the generic error, e.g. "Price impact calculation unknown"
- log the error message from the SDK in Sentry
- show button to assume unknown price risk and proceed
**if there is a price impact error and query error:**
- Show query error message from the SDK
=> fix: display unknown price impact for swap PI errors

packages/lib/modules/pool/actions/remove-liquidity/queries/useRemoveLiquidityBuildCallDataQuery.ts
console.logging the permit is useful for debugging edge-case issues.
=> chore: console.log permit in remove query when it does exist

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx, packages/lib/modules/pool/actions/add-liquidity/queries/useAddLiquidityPriceImpactQuery.ts, packages/lib/modules/pool/actions/add-liquidity/queries/useAddLiquiditySimulationQuery.ts, packages/lib/modules/swap/handlers/DefaultSwap.handler.ts, packages/lib/shared/components/errors/GenericError.tsx, packages/lib/shared/components/errors/UnbalancedAddError.tsx, packages/lib/shared/services/api/swap.graphql, packages/lib/shared/utils/error-filters.ts, packages/lib/shared/utils/query-errors.ts
Note that we will display the alert and "advice" the user to use proportional inputs in this cases: 
- v3 vault invariant errors
- v2 unbalanced error 
https://github.com/user-attachments/assets/55f844ff-f439-43ee-b8ed-256cb04d7f65
This PR also fixes a GraphQL field  deprecation (`queryBatchSwap` field)
=> feat: handle v3 invariant add errors

.github/workflows/checks.yml, packages/lib/modules/transactions/transaction-steps/receipts/receipt.hooks.integration.spec.ts
Once cached, the workflows are faster than in ubuntu and integration anvil tests looks more reliable 🤞
=> feat: use M1 runner in GHA CI

packages/lib/modules/tokens/TokenInput/TokenInput.tsx, packages/lib/modules/user/settings/UserSettings.tsx
Fixes 2 QA issues: 
- 50% max slippage input
- No negative sign when price impact is zero
=> fix: slippage inputs & price impact sign

packages/lib/modules/pool/PoolDetail/PoolInfo/PoolAttributes/useFormattedPoolAttributes.tsx, packages/lib/modules/pool/pool.helpers.ts, packages/lib/shared/services/api/pool.graphql, packages/lib/shared/services/api/pools.graphql
=> feat: add swap fee manager

packages/lib/modules/pool/actions/add-liquidity/form/useProportionalInputs.tsx, packages/lib/modules/transactions/transaction-steps/useSignPermit2Step.tsx
Pool to reproduce: 
https://test.balancer.fi/pools/sepolia/v3/0xa8c18ce5e987d7d82ccaccb93223e9bb5df4a3c0/add-liquidity
**Before:** 
https://github.com/user-attachments/assets/e962673c-91e4-4746-9e8b-888e833151c7
**After:** 
https://github.com/user-attachments/assets/bd1a19c5-946e-47d2-b140-1a07ddba1ec6
=> fix: keep user input when calculating proportional inputs

packages/lib/modules/pool/actions/add-liquidity/useAddLiquidityStep.tsx, packages/lib/modules/pool/actions/remove-liquidity/useRemoveLiquidityStep.tsx, packages/lib/modules/price-impact/PriceImpactAccordion.tsx, packages/lib/modules/swap/useSwapStep.tsx, packages/lib/modules/transactions/transaction-steps/TransactionStepButton.tsx, packages/lib/modules/web3/contracts/useManagedSendTransaction.ts, packages/lib/shared/components/errors/UnbalancedError.test.tsx
Running `useManagedSendTransaction` hook with `undefined` `txConfig` was causing weird issues. 
It does not make sense to run that code when the txConfig is not ready so better to render a disabled button in that case.
=> fix: avoid default mainnet.id in useManagedSendTransaction

packages/lib/modules/pool/actions/remove-liquidity/queries/useRemoveLiquidityPriceImpactQuery.ts, packages/lib/modules/price-impact/PriceImpactAccordion.tsx, packages/lib/modules/price-impact/PriceImpactProvider.tsx, packages/lib/modules/price-impact/price-impact.utils.ts
**"Price Impact exceeds label" was wrong.** 
- Refactored to a function to make it clearer. 
- Moved related functions to the same file for more cohesion 
- We won't use `medium` for now but the code is clearer.
**Remove query keys were not using debounced input** 
Fixes [QA functional issue # 15](https://www.notion.so/QA-Testing-109e395e228180a494edf9a1fdd11027#a0a12105b0004628a0361033ea0fe72e)
=> fix: price impact exceeds percentage

packages/lib/modules/pool/actions/add-liquidity/handlers/ProportionalBoostedAddLiquidityV3.handler.ts, packages/lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx, packages/lib/shared/utils/numbers.ts
Before: 
Simulation error when bpt to remove was too small.
After:
Simulation and button are disabled:
=> fix: disable remove when remove usd is too small

packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/usePoolCharts.tsx, packages/lib/modules/pool/PoolDetail/PoolUserEvents.tsx
Now we can see pool swaps in "My transactions":
=> feat: display swap events in My transactions (pool user events)

packages/lib/modules/pool/actions/add-liquidity/AddLiquidityProvider.tsx, packages/lib/modules/price-impact/price-impact.utils.ts
Nested pool to reproduce: 
http://test.balancer.fi/pools/sepolia/v3/0x693cc6a39bbf35464f53d6a5dbf7d6c2fa93741c/add-liquidity
Adding in some nested pool causes many Price Impact calculation errors like this:
```
Unexpected error while calculating addLiquidityUnbalancedBoosted PI at Swap step:
Error: Unexpected error while calculating addLiquidityUnbalancedBoosted PI at Delta add step:
ContractFunctionExecutionError: The contract function "queryAddLiquidityUnbalancedToERC4626Pool" reverted.
Error: WrapAmountTooSmall(address wrappedToken)
(0x8A88124522dbBF1E56352ba3DE1d9F78C143751e)
Contract Call:
address:   0xc6674C0c7694E9b990eAc939E74F8cc3DD39B4b0
function:  queryAddLiquidityUnbalancedToERC4626Pool(address pool, uint256[] exactUnderlyingAmountsIn, address sender, bytes userData)
args: …
```
=> fix: unblock nested add when the PI calculation fails

packages/lib/modules/swap/SwapProvider.tsx
Avoid selecting wallet chain in case of pool swap. 
**Before**: In pool swaps we were using the connected wallet chain instead of the `pool.chain`. 
**After**:  Now the right pool chain is always used, so chain switch is properly detected:
=> fix: avoid selected chain change when pool swap

packages/lib/modules/pool/pool.helpers.ts
is `isBoosted` logic exclusive to v3? Please confirm before merging. 
https://balancerecosystem.slack.com/archives/C02F9EMRKQA/p1733775808481719
=> fix: isBoosted should only apply to v3 pools

packages/lib/modules/tokens/TokenInput/TokenInput.tsx
Scroll from inside the token input was causing weird issues as it was changing the numeric value of the input.
=> fix: avoid token input value change onScroll

packages/lib/modules/pool/actions/LiquidityActionHelpers.integration.spec.ts, packages/lib/modules/pool/pool.helpers.ts
Fixes token helpers for !v3 pools with `ERC4626`. 
Pool to test:
https://mono-test-v3-git-fix-v2boosted-balancer.vercel.app/pools/gnosis/v2/0xbc2acf5e821c5c9f8667a36bb1131dad26ed64f9000200000000000000000063
=> fix: avoid underlying tokens in not v3 pools

packages/lib/modules/pool/tags/getPoolTags.ts
We will undo this change with this PR once we finish setting all the tags up.
=> chore: temporary use 5 minutes tag cache until we deploy all tags for V3 release

packages/lib/modules/pool/PoolDetail/PoolInfo/Erc4626Info.tsx, packages/lib/modules/pool/PoolDetail/PoolInfo/PoolContracts.tsx
- also update text
for example with [this pool](https://balancer.fi/pools/gnosis/v2/0xbc2acf5e821c5c9f8667a36bb1131dad26ed64f9000200000000000000000063):
=> fix: hide erc4626 info for protocol version < 3

packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx, packages/lib/modules/pool/pool.utils.ts
Replaces pool name use for boosted pools with display tokens and weights so we can distinguish between weighted/stable.
In screenshots below, ignore sepolia pools and focus on Gnosis.
Before:
After:
=> fix: Use display tokens for boosted pools

apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/layout.tsx, apps/beets-frontend-v3/app/(app)/portfolio/[chain]/page.tsx, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/layout.tsx, apps/frontend-v3/app/(app)/portfolio/[chain]/page.tsx, packages/lib/modules/pool/PoolDetail/PoolActivity/usePoolActivity.tsx, packages/lib/modules/pool/PoolDetail/PoolActivityChart/usePoolActivityChart.tsx, packages/lib/modules/pool/pool.utils.ts, packages/lib/modules/swap/SwapLayout.tsx, packages/lib/modules/swap/SwapProvider.tsx
Improves safety by enforcing chain slug check. 
Example of wrong url: 
https://mono-test-v3-git-fix-chainslugs-balancer.vercel.app/pools/mainnet/v2/0x3de27efa2f1aa663ae5d458857e731c129069f29000200000000000000000588
Before: 
After: 
TODO: 
- improve API error handling for other cases
=> fix: improve chainSlug handling

packages/lib/modules/pool/actions/add-liquidity/useAddLiquiditySteps.tsx, packages/lib/modules/transactions/transaction-steps/receipts/receipt-parsers.ts, packages/lib/modules/transactions/transaction-steps/receipts/receipt.hooks.integration.spec.ts, packages/lib/test/anvil/anvil-setup.ts, packages/lib/test/anvil/testWagmiConfig.tsx, packages/lib/test/utils/wagmi/wagmi-test-clients.ts
- New setup for gnosis integration tests
- Dirty solution for EUR.e until we properly implement it here: https://github.com/balancer/frontend-monorepo/issues/292
We already had that issue in V2 pools:
https://test.balancer.fi/pools/gnosis/v2/0xdd439304a77f54b1f7854751ac1169b279591ef7000000000000000000000064 
V3 pool: 
https://test.balancer.fi/pools/gnosis/v3/0xecc5aebd9569c82a0944007b22d03801a8fdfe99/add-liquidity/0x09ad952e0b5302f00061e7f9b68849b395a502787585c48ac9148ef511ba05c9
=> fix: avoid duplicated EURe in adds receipt

packages/lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx, packages/lib/modules/pool/pool.helpers.ts, packages/lib/shared/components/poppover/BalPopover.tsx
Do we prefer an alert with all the reasons?
If we go for the tooltip there are two Add liquidity buttons.
Example:
=> feat: add tooltip for blocked add button

packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx
See this pool https://balancer.fi/pools/ethereum/v2/0x1d13531bf6344c102280ce4c458781fbf14dad140000000000000000000006df
We don't look at erc4626 underlying tokens for v2 pools. Other parts of the pool page have been fixed, the last part is just the pills.
I have more work todo around this issue, so the conditional will probably be extracted in a future PR.
=> fix: Dont display underlying for v2 pools

packages/lib/modules/pool/PoolDetail/PoolActivity/poolActivity.types.ts, packages/lib/modules/pool/PoolDetail/PoolActivity/usePoolActivity.tsx, packages/lib/modules/pool/PoolDetail/PoolActivityTable/PoolActivityTable.tsx
fix broken sorting in pool events table
check https://balancer.fi/pools/ethereum/v2/0xcfca23ca9ca720b6e98e3eb9b6aa0ffc4a5c08b9000200000000000000000274
=> fix: pass original id to pool activity table

apps/frontend-v3/.env.test, packages/lib/modules/pool/PoolDetail/PoolInfo/PoolContracts.tsx, packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx, packages/lib/modules/pool/__mocks__/notAllowedPoolMock.ts, packages/lib/modules/pool/actions/LiquidityActionHelpers.integration.spec.ts, packages/lib/modules/pool/pool.helpers.ts, packages/lib/shared/services/api/pool-tokens.graphql
Pool to test:
https://mono-test-v3-git-feat-isbufferallowed-balancer.vercel.app/pools/ethereum/v3/0x6649a010cbcf5742e7a13a657df358556b3e55cf
Now token pills are correct (no underlying tokens): 
Tokens in adds are correct: 
No tokenized vaults:
=> feat: isBufferAllowed logic

packages/lib/modules/tokens/TokenInput/TokenInput.tsx, packages/lib/modules/tokens/TokenSelectModal/TokenSelectList/TokenSelectListRow.tsx
If you try to input a number before a token is selected you get this error. We can fix this by disabling the input until a token is selected. I'm not sure if this will cause issues elsewhere. It shouldn't.
We can hide this input gradient when no token is selected to avoid this weird shadow issue.
=> chore: Minor fixes

packages/eslint-config/next.js
We have a lot of exceptions for warnings of max-len rule in svgs etc where they should really be ignored. This rule change should remove that warning.
=> chore: Update eslint rules

packages/lib/modules/pool/actions/remove-liquidity/handlers/RecoveryRemoveLiquidity.handler.ts, packages/lib/package.json, pnpm-lock.yaml
Bump version to unblock sonic launch. 
TODO: 
we will use added sdk features (wethIsEth for Boosted and so on) in a separate PR.
=> chore: bump sdk to 1.0.1

packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx
fixes #402 
reset to page 1 (set skip to 0) on _any_ pool filter change (except (un)ticking **My Liquidity** as this already does the reset)
=> fix: reset to page 1 on pool filter change

packages/lib/shared/components/modals/ActionModalFooter.tsx
bug [context](https://balancerecosystem.slack.com/archives/C02F9EMRKQA/p1736221312345609)
we need to provide key to create new RenderActionButton's instance depending on currentStep.id otherwise it may take previous transaction result from `useManagedTransaction`
=> fix: transaction action button

apps/beets-frontend-v3/.lintstagedrc.mjs, apps/frontend-v3/.lintstagedrc.mjs, packages/lib/.eslintrc.js, packages/lib/.lintstagedrc.mjs
The next.js eslint setup is explicitly ignoring linting for `*.js` files. 
This PR also ignores `*.js` files in `.lintstagedrc` config files. 
Also adds  rule  '@next/next/no-html-link-for-pages': 'off', to lib eslint to avoid another issue.
=> fix: ignore js files in lint staged

apps/beets-frontend-v3/app/(app)/layout.tsx, apps/beets-frontend-v3/app/(app)/pools/layout.tsx, apps/beets-frontend-v3/app/(marketing)/layout.tsx, apps/beets-frontend-v3/app/layout.tsx, apps/beets-frontend-v3/app/layouts/base-layout.tsx, apps/beets-frontend-v3/app/not-found.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx
this is a temporary fix for:
1. the beets app is getting a lot of requests that route to `/_not-found`
2. the beets app is loading the lzbeets migration modal on _all_ pages
these 2 combined are generating a lot of rpcs calls
so to exclude the modal when rendering the not-found and marketing page i did this:
- updated root layout to only proved html structure
- created base layout with client components prev in root layout and a flag for conditional rendering of modal 
(imported by app & marketing layout and not-found page)
also fixed always setting skip on pools page to zero and moved `PoolsNetworkWatcher` to pools page
=> fix: add base layout

packages/lib/modules/pool/pool.helpers.ts
`token.isAllowed` only applies for v2 pools.
=> fix: Only apply token.isAllowed for v2

packages/lib/modules/tokens/__mocks__/AppGlobalData.builders.ts, packages/lib/shared/services/api/global.graphql, packages/lib/shared/services/api/protocol-stats.graphql
the api is deprecating 2 fields that aren't actively used in the frontend
- totalSwapVolume
- totalSwapFee
=> fix: remove unused props

apps/beets-frontend-v3/app/middleware.ts, apps/beets-frontend-v3/middleware.ts, apps/beets-frontend-v3/next.config.js
1. block 'old' api requests:
- `/api/rpc/FANTOM/routes`
- `/api/rpc/OPTIMISM/routes`
2. add `referer` msg to rest of the api requests
=> fix: block certain api requests for beets

packages/lib/shared/utils/query-errors.ts
Ignores this frequent issue in sentry: 
https://balancer-labs.sentry.io/issues/5990859796/?project=4506382607712256&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20level%3Afatal&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=0
=> chore: ignore metamask pending connection error

packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx
Uses pool icon from metadata if provided with a pool name.
Example pool: https://mono-frontend-v3-git-chore-use-pool-icon-balancer.vercel.app/pools/ethereum/v3/0x10a04efba5b880e169920fd4348527c64fb29d4d
=> chore: Use pool icon if provided

packages/lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx
=> feat: Use pool descriptions

packages/lib/modules/swap/SwapProvider.tsx, packages/lib/modules/tokens/TokenInput/TokenInput.tsx
Fixes 2 swap issues:
1. validate inputs after userAddress changes
2. avoid app crashing when a url with tokenAmountIn is copy-pasted
Example loading this URL: swap/zkevm/rETH/wstETH/0.0136547066055
Before: 
After:
=> fix: validate inputs after userAddress changes

apps/frontend-v3/lib/services/chakra/ThemeProvider.tsx
It appears that using a key on the ChakraProvider that changes, when the theme changes causes some kind of full rerender that, causes the wallet to disconnect. I guess that somehow that rerender messes with the wagmi providers that are nested below.
To test:
1. connect a wallet on the portfolio page that has a CoW pool position. 
2. Click the table row to navigate to the CoW pool.
3. The wallet should not disconnect.
Currently on production if you follow the same flow the wallet disconnects.
=> fix: Account disconnect on theme change

packages/lib/modules/pool/actions/add-liquidity/modal/AddLiquiditySummary.tsx
In add liquidity success state on the BAL 8020 pool we are showing two CTAs.
We should only show the one that references locking for the bal pool.
=> fix: Only show one CTA for BAL8020

apps/beets-frontend-v3/lib/services/chakra/themes/beets/beets.theme.ts
#458 is setting light mode by default for beets
but beets doesn't have a light mode...
so setting dark mode as default here
**_please let me merge it so i can set "Auto-assign Custom Production Domains" back to enabled first (beets deployment is currently rolled back)_**
=> fix: set beets color mode to dark

packages/lib/modules/pool/pool.helpers.spec.ts, packages/lib/modules/pool/pool.helpers.ts
`pool.hasAnyAllowedBuffer` check must be applied later to avoid shadowing other checks
=> fix: hasAnyAllowedBuffer check

apps/beets-frontend-v3/next.config.js, apps/frontend-v3/next.config.js, turbo.json
Skipping setry setup in CI builds should save some time.
=> chore: avoid sentry setup in CI

packages/lib/modules/swap/useSwapSteps.tsx, packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx
Unwrapping native asset does not require approvals anymore:
=> Avoid approvals when unwrapping WETH

packages/lib/modules/pool/pool.helpers.ts
We currently allow the weth/eth choice in the add liquidity form for pools that contain erc4626 tokens. Apparently the router doesn't support this so we need to restrict that functionality to pools that do not contain erc4626 tokens.
=> fix: Don't allow eth adds for erc4626 pools

packages/lib/config/config.types.ts, packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts, packages/lib/modules/swap/SwapSimulationError.tsx
- add supported networks for cow swap to project config
- show cow swap link only for pools on a cow supported network
network (SONIC) _is not supported_ by cow:
network (MAINNET) _is supported_ by cow:
=> feat: add cow supported networks

apps/frontend-v3/app/(app)/lbp/create/page.tsx, apps/frontend-v3/app/(app)/lbp/layout.tsx, apps/frontend-v3/app/(app)/lbp/page.tsx, apps/frontend-v3/lib/components/navs/NavBarContainer.tsx
Adds root LBP page (/lbp) with link to create lbp page (/lbp/create) and a link to the root page in the navbar. The nav link and access to the pages are hidden/blocked on production.
=> chore: Init LBP pages

packages/lib/modules/web3/WagmiConfig.tsx, packages/lib/modules/web3/Web3Provider.tsx, packages/lib/shared/components/site/providers.tsx
Hypothesis: 
Using the `wagmiConfig` after checking `useIsMounted` instead of passing it through a prop could avoid some disconnection problems due to re-renders.
=> fix: avoid passing wagmiConfig as a prop

packages/lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.spec.tsx, packages/lib/modules/pool/actions/remove-liquidity/useRemoveLiquiditySteps.tsx, packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx, packages/lib/modules/transactions/transaction-steps/TransactionStepButton.tsx, packages/lib/modules/web3/contracts/useManagedErc20Transaction.ts, packages/lib/modules/web3/contracts/useManagedTransaction.ts, packages/lib/modules/web3/safe.hooks.tsx
Signing standard permit approvals is not possible with Smart Accounts (including Safe):
>  Regular permits (EIP-2612) cannot be directly signed by Gnosis Safe contracts - they can only be signed by EOAs. This is because EIP-2612 permits specifically require ECDSA signatures (specifically eth_sign/personal_sign type signatures), while Gnosis Safe uses contract-based signatures.
> The main reasons:
> Regular permits expect r, s, v components from ECDSA signatures
> Gnosis Safe uses a different signing scheme (contract-based signatures via EIP-1271)
> EIP-2612's permit function validates signatures using ecrecover
> Permit2 works with Gnosis Safe because it was specifically designed to support both EOA signatures and EIP-1271 contract signatures. When using Permit2, the contract checks if …
=> fix: v3 Safe removes approve BPT with approval tx instead of permit signature

packages/lib/modules/web3/AcceptPoliciesModal.tsx
The old useEffect was triggering disconnections in cases where they were not needed causing different issues like: 
https://github.com/balancer/frontend-monorepo/issues/61#issue-2587970801
=> fix: wrong disconnections in AcceptPolicies modal

packages/lib/modules/pool/PoolDetail/PoolComposition.tsx, packages/lib/modules/pool/pool-tokens.utils.spec.ts, packages/lib/modules/pool/pool-tokens.utils.ts
Pools to test: 
`pools/gnosis/v2/0x66888e4f35063ad8bb11506a6fde5024fb4f1db0000100000000000000000053`
`pools/ethereum/v2/0x49cbd67651fbabce12d1df18499896ec87bef46f00000000000000000000064a
`
**Before**: 
**After**:
=> fix: exclude phantom btp in composable stable pool display

packages/lib/shared/hooks/useAprTooltip.ts
Implements all text changes suggested in the designs linked here #563.
- Does not include links in tooltips. For some reason links are not clickable within these tooltips and if you click on them within the pool list they redirect to the pool page regardless of the href.
- Does not include Core pool attribute in pool info, this is not available in the API yet.
=> chore: Update tooltips

packages/lib/modules/pool/tags/PoolTags.tsx, packages/lib/shared/utils/numbers.ts
the current ui checks if the points multiplier value is an integer
however the value for rings is 1.5 so therefore it isn't rendered
before:
after:
=> fix: show decimals for points value

packages/lib/modules/pool/tags/getPoolTags.ts
=> fix: Update metadata type to match repo

apps/beets-frontend-v3/next.config.js
only redirects to OP pools because Aura will probably be the main referer here
will be removed when Aura updates their links to these pools
=> fix: add redirect for old pool links

packages/lib/config/projects/beets.ts, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx, packages/lib/modules/pool/pool.types.ts
A few weeks ago we discussed over Slack about having a category to highlight RWA pools. I've just done the obvious changes but might've missed something. Metadata PR has been merged https://github.com/balancer/metadata/pull/46
=> add rwas filter

packages/lib/modules/pool/actions/add-liquidity/AddLiquidityProvider.tsx, packages/lib/modules/pool/actions/add-liquidity/form/useProportionalSlippage.tsx, packages/lib/modules/tokens/TokenBalancesProvider.tsx
Some users reported an `TRANSFER_FROM_FAILED` errors when adding liquidity in proportional pools  (using max balance)
https://discord.com/channels/638460494168064021/1340181683172806768/1340181687342202880
There were 2 root causes: 
- The max amount in the case of tokens with 6 decimals requires an extra bufferPercentage margin error to avoid going over the user's balance. Fixed by adding `5n` extra for a bigger error margin.
- When the user changes the slippage in proportional mode,  the bufferPercentage was not being recalculated.  Fixed by clearing the input amounts in this specific edge case.
=> fix: slippage and rounding issues when using bufferPercentage in proportional adds

apps/frontend-v3/app/(app)/debug/impersonate/page.tsx, apps/frontend-v3/app/(app)/debug/page.tsx, apps/frontend-v3/public/images/logos/mock.svg, packages/lib/modules/web3/ImpersonateAccount.tsx, packages/lib/modules/web3/WagmiConfig.tsx, packages/lib/modules/web3/WagmiConfigProvider.tsx, packages/lib/modules/web3/Web3Provider.tsx, packages/lib/modules/web3/wallet-connect/createMockConnector.ts, packages/lib/shared/components/navs/NavBar.tsx, packages/lib/shared/components/site/providers.tsx
Only in dev and test (staging) environments: 
1. New option in Rainbow to impersonate with default anvil wallet:
2. Custom page to impersonate with any address:
https://github.com/user-attachments/assets/c5a5a623-f028-49d8-bb28-19c5b55bbe8b
=> feat: impersonate account

packages/lib/modules/pool/__mocks__/pool-examples/boosted.ts, packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx, packages/lib/shared/hooks/useAprTooltip.spec.tsx, packages/lib/shared/hooks/useAprTooltip.ts
Example: 
https://mono-test-v3-git-feat-merkelincentivesbytoken-balancer.vercel.app/pools/ethereum/v3/0x10a04efba5b880e169920fd4348527c64fb29d4d
=> feat: split Merkl incentives by token

apps/beets-frontend-v3/lib/services/chakra/themes/beets/beets.theme.ts, apps/beets-frontend-v3/package.json, apps/frontend-v3/lib/services/chakra/themes/bal/bal.theme.ts, apps/frontend-v3/lib/services/chakra/themes/cow/cow.theme.ts, apps/frontend-v3/package.json, packages/lib/package.json, packages/lib/shared/services/chakra/themes/base/foundations.ts, pnpm-lock.yaml
Renaming from config to themeConfig fixes the following deprecation warning in turbopack mode:
=> fix: foundation turbopack error

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx, packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx, packages/lib/modules/pool/actions/add-liquidity/queries/useAddLiquidityPriceImpactQuery.ts, packages/lib/modules/pool/pool.helpers.ts, packages/lib/modules/price-impact/price-impact.utils.ts, packages/lib/shared/app/react-query.provider.tsx, packages/lib/shared/components/errors/UnbalancedAddError.tsx, packages/lib/shared/utils/error-filters.ts, packages/lib/shared/utils/query-errors.ts
We cannot know in advance when a pool with stable surge hook is surging, but we can parse SDK error (that in turn, comes from viem) and:
- Show a proper error
- Avoid sending sentry errors in this cases 
Current example of pool surging: 
[/pools/arbitrum/v3/0xc2b0d1a1b4cdda10185859b5a5c543024c2df869/add-liquidity](https://mono-frontend-v3-git-feat-disableflexiblewhensurging-balancer.vercel.app/pools/arbitrum/v3/0xc2b0d1a1b4cdda10185859b5a5c543024c2df869/add-liquidity)
=> feat: manage unbalanced add errors when pool is surging

packages/lib/modules/pool/PoolDetail/PoolActivity/usePoolActivity.tsx
Fix the activity chart to adjust the min/max values when you toggle the activity type. Currently it does not, so you end up with situations where all swaps are clumped together because there is a big add that is significantly larger than any swap
before:
after:
You can see below that the pool has a very large add:
=> Adjust the chart min/max when the activity type is toggled

packages/lib/modules/eclp/useGetECLPLiquidityProfile.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolCharts.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/useEclpPoolChart.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/usePoolCharts.tsx, packages/lib/shared/utils/numbers.ts
- invert price button
- styling updates
- no chart data fix
- isloading update
- increase margin slightly for `poolIsInRange` check
=> fix: switch clp price

packages/lib/modules/transactions/transaction-steps/TransactionStepButton.tsx, packages/lib/modules/transactions/transaction-steps/safe/TransactionBatchButton.tsx, packages/lib/modules/transactions/transaction-steps/transaction-button.helpers.ts
We were showing a wrong smart account related loading label when using an EOA.
=> fix: transaction button loading label for smart accounts

packages/lib/modules/pool/pool.helpers.spec.ts, packages/lib/modules/pool/pool.helpers.ts
On https://github.com/balancer/frontend-monorepo/pull/727 a bug was introduced, Sepolia pools that should be exempted of add liquidity blocks were able to be blocked. These changes fix that.
=> [#742] add exception for Sepolia when blocking pool add liquidity

packages/lib/modules/tokens/TokenRow/TokenRow.tsx
- allow overflow for logo-in-logo images
- round square images a bit
=> fix: token image optimization

packages/lib/modules/transactions/transaction-steps/receipts/receipt-parsers.ts
Fixed 2 issues found in the last QA round: 
1. [stable pool, remove single token] if remove 100% of 1 token, there is an empty token displayed on the Confirm screen (due to the Monerium EURe implementation):
7. [Sepolia, [stable pool](https://mono-test-v3-git-feat-safebatchadds-balancer.vercel.app/pools/sepolia/v3/0x64bb1613459c6790cd6c94272dc9d09384d955c9), remove  liquidity] I’ve removed liquidity (USDC and ETH), but the confirm modal shows USDC only.
=> fix: remove parser for EURe and balancer router removes

packages/lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx, packages/lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx
- disable the empty tooltip below the button when there are no blocking reasons to show
=> fix: do not show empty tooltip

packages/lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx, packages/lib/shared/components/errors/RemoveSimulationError.tsx, packages/lib/shared/utils/error-filters.ts
Relax `isAfterAddUnbalancedHookError` and `isSingleRemoveHookError` conditions to ensure that we don't miss any surging error.
=> fix: simplify stable surge error handling

packages/lib/modules/tokens/approvals/permit2/usePermit2ApprovalSteps.tsx
Some chains are not yet configured for permit2 cause as we didn't deploy v3 on them.
That implies optional permit2Address and some defensive checks.
=> chore: avoid error when permit2Address in undefined

packages/lib/config/networks/sepolia.ts, packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx, packages/lib/modules/web3/useTokenAllowances.tsx
Expose `isRefetching` to indicate that allowance refetch is still in progress so that consumers wait more. 
This was affecting to `onSuccess` callback using refetch allowances before they had finished.
=> fix: handle allowance refetching delay

package.json, packages/lib/package.json, packages/lib/shared/services/api/apollo.client.ts, pnpm-lock.yaml
- bump @apollo/experimental-nextjs-app-support from 0.11.3 to 0.11.11
- `ssrMode` is no longer needed
- bump turbo from 2.3.3 to 2.4.4
- bump vitest from 3.0.5 to 3.0.9
- bump @graphql-codegen/typescript-document-nodes from 4.0.9 to 4.0.15
=> chore: update packages dependabot

packages/lib/modules/pool/actions/LiquidityActionHelpers.spec.ts, packages/lib/modules/pool/actions/LiquidityActionHelpers.ts
Closes [#818](https://github.com/balancer/frontend-monorepo/issues/818)
V3 Smart contracts do not depend on pool type so we can skip calling `mapPoolType` from the SDK to avoid exclusive V3 pool types (like `QuantAMMWeigthed`) failing in that method.
=> fix: avoid mapPoolType for V3 pools

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, packages/lib/package.json, pnpm-lock.yaml
- bump nextjs-toploader from 1.6.12 to 3.8.16
- bump @graphql-codegen/cli from 5.0.2 to 5.0.5
- bump react-hook-form from 7.54.2 to 7.55.0
- bump vitest-mock-extended from 2.0.2 to 3.0.1
=> chore: bump npm packages

packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/modules/vebal/vote/VoteList/VoteListFilters.tsx, packages/lib/modules/vebal/vote/VoteList/VoteListLayout.tsx, packages/lib/modules/vebal/vote/VoteList/VoteListProvider.tsx, packages/lib/modules/vebal/vote/VoteList/useVoteListFiltersState.tsx
Closes #802 by adding pool protocol version filter to voting list. 
There are other potential filters (like hooks & `minTVL`) to be copied from pool list but I think this is enough. 
https://github.com/user-attachments/assets/724cd974-d179-498c-a73a-db7187239f6f
=> feat: add pool version filter to pool voting list

packages/lib/modules/pool/PoolDetail/PoolHeader/PoolAdvancedOptions.tsx
Now the user will be able to get to the swap page no matter if add liquidity action is blocked. 
If the pool is not yet available for swap in the SOR, they will get a swap error but that's independent of the add liquidity state.
Slack conversation with more context: 
https://balancerecosystem.slack.com/archives/C02F9EMRKQA/p1744219528580369?thread_ts=1744053305.178429&cid=C02F9EMRKQA
=> feat: allow pool swaps even when pool adds are blocked

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, packages/e2e-tests/tests/dev/add-liquidity.spec.ts, packages/lib/config/networks/arbitrum.ts, packages/lib/config/networks/avalanche.ts, packages/lib/config/networks/base.ts, packages/lib/config/networks/fantom.ts, packages/lib/config/networks/fraxtal.ts, packages/lib/config/networks/gnosis.ts, packages/lib/config/networks/mainnet.ts, packages/lib/config/networks/mode.ts, packages/lib/config/networks/optimism.ts, packages/lib/config/networks/polygon.ts, packages/lib/config/networks/sepolia.ts, packages/lib/config/networks/sonic.ts, packages/lib/config/networks/zkevm.ts, packages/lib/modules/eclp/hooks/useGetTokenRates.tsx, packages/lib/modules/pool/actions/LiquidityActionHelpers.spec.ts, packages/lib/modules/pool/pool.helpers.ts, packages/lib/modules/pool/queries/usePoolEnrichWithOnChainData.tsx, packages/lib/modules/pool/queries/useUserUnstakedBalance.tsx, packages/lib/package.json, packages/lib/test/anvil/customSlots.ts, packages/lib/test/utils/wagmi/fork-default-balances.ts, packages/lib/test/utils/wagmi/fork-options.ts, pnpm-lock.yaml
The last sdk version has important breaking changes as it exports addresses in a different way: 
Context: https://github.com/balancer/b-sdk/pull/644
=> feat: migrate to breaking changing sdk v3.1.0

packages/lib/modules/pool/PoolList/PoolListFilters.tsx
this prevents a subpath from being added to beets which then didn't open the url after a button click
=> fix: only add subpath to pool composer url for balancer

packages/lib/modules/vebal/lock/steps/useLockStep.integration.spec.tsx, packages/lib/modules/vebal/lock/steps/useLockStep.tsx, packages/lib/modules/vebal/lock/steps/useLockSteps.tsx, packages/lib/modules/vebal/vote/useVeBALBalance.ts, packages/lib/modules/web3/UserAccountProvider.tsx, packages/lib/modules/web3/impersonation/TimeMocker.tsx, packages/lib/modules/web3/impersonation/useImpersonateAccount.ts, packages/lib/test/utils/wagmi/fork.helpers.ts
Fixes 2 issues with lock step flows: 
1. When only extending lock date but not increasing locked amount we must ignore token approval steps. 
2. refetches balances (veBal pool balance in this context) query on lock step success. 
Also adds small improvements to impersonator hook.
=> fix: lock step token approvals and onSuccess callback

packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx
The animations for the APR popover lose performance when too many components inside. Passing animation parameters through _motionProps_ directly seems to fix the issue.
=> Fix popover animations losing frames

packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolChartsProvider.tsx, packages/lib/shared/utils/time.ts
Fixes #419
- timestamps from API are UTC midnight 
- example: `1743750000` which is `Fri, 04 Apr 2025 00:00:00 GMT`
- echarts defaults to interpreting timestamp values in local timezone of user
-  converts `1743750000` to `Thu Apr 03 2025 17:00:00 GMT-0700 (Pacific Daylight Time)`
- adjusted timestamp by the offset from UTC to account for echarts limitation
=> Fix pool chart date display

packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx
With custom animations the popover was shown on mount instead of waiting for the hover trigger.
=> Avoid showing stake popover on mount

apps/frontend-v3/lib/vebal/lock/duration/useLockDuration.ts, apps/frontend-v3/lib/vebal/lock/form/VebalLockForm.tsx
Closes #937 
On certain edge cases could previously return less veBAL than previously held.
=> [#937] set the right min slider value when extending veBAL lock

packages/lib/shared/services/api/swap.graphql
On certain cases an error was returned by the API and right now we are not really using this data.
=> Remove pool symbol from sor paths query

packages/lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkPoolsLayoutWrapper.tsx, packages/lib/modules/tokens/TokenRow/TokenRowGroup.tsx
- filter pools with claims earlier so 'claim all' and 'claim' per pool are only set when needed
- aggregate amounts for the same token
before:
after:
=> fix: portfolio claim incentives

apps/beets-frontend-v3/app/(app)/pools/page.tsx, packages/lib/shared/components/other/AnimatedNumber.tsx, packages/lib/shared/components/other/Stat.tsx, packages/lib/shared/pages/PoolsPage/PoolPageStats.tsx, packages/lib/shared/pages/PoolsPage/PoolsPage.tsx, packages/lib/shared/services/api/protocol-stats.graphql, packages/lib/shared/utils/numbers.ts
- Replaced the "Swap fees" stat with 'Yield (24h)'
- Added `surplus24h` from the API to `protocol-stats.graphql`
- Added a hover state to show the breakdown of the Yield stat which shows
- Swap fees
- Yield-bearing tokens
- Added a number animation on page load
=> Pools page hero stats

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, package.json, packages/lib/package.json, pnpm-lock.yaml
- bump autoprefixer to 10.4.21
- bump husky to 9.1.7
- removed @tanstack/react-table (unused)
=> chore: bump packages

packages/lib/modules/eclp/hooks/useGetECLPLiquidityProfile.tsx
fix edge case where the lower bound of an eclp is zero
reversing the chart then tried to go to infinity (and beyond)
before:
after:
=> fix: filter out zero price to prevent infinity

packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx, packages/lib/shared/components/tooltips/apr-tooltip/TooltipAprItem.tsx
before:
after (moved the tooltip too):
=> fix: don't show a line when reward token is unknown

.github/workflows/checks.yml, packages/test/anvil/anvil-setup.ts
Our dev e2e tests for adding in the tri boosted pool started failing after the pectra upgrade.
The issues does not happen in production or tenderly virtual testnets but only in anvil forks. 
This PR points to a block number from May 6th 2025 until foundry fixes the issue. 
We registered the issue in their telegram, sent this [reproduction repo](https://github.com/agualis/boosted-add-demo)) and now they are investigating.
=> Add pre pectra fork block number in mainnet

.github/workflows/checks.yml, packages/lib/test/utils/wagmi/fork.helpers.ts, packages/test/anvil/anvil-setup.ts
From foundry team: 
> so for 7702 accounts, it would make sense if permit2 starts failing.
Because if the EOA is authorized, instead of using ECDSA.recover, the permit2 SignatureChecker lib would use 1271 signature verification first.
So indeed the first anvil account has 7702 auth lists https://etherscan.io/address/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266#authlist7702
So the workaround is using an anvil account that does not have 7702 auth lists. For instance:
`0x90F79bf6EB2c4f870365E785982E1f101E93b906`
https://etherscan.io/address/0x90F79bf6EB2c4f870365E785982E1f101E93b906#authlist7702 --> no 7702 tab
=> fix: change default impersonation anvil account to one without 7702

apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/incentivesBlacklist.ts, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/myVotes.helpers.ts
We don't have `noUncheckedIndexedAccess` rule activated so accessing 
`blacklistedVotes[vote.gauge.address]` [here](https://github.com/balancer/frontend-monorepo/blob/9b05fb0284abed1eeb8f60fd52a30443289afa61/apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx#L164) always returns BigNumber type even if the record is empty.
Casting the result of the hook from `Record<string, BigNumber>` to `Record<string, BigNumber | undefined>` fixes the issue but the proper way would be activating `noUncheckedIndexedAccess` (which could be done in increments).
=> fix: avoid undefined blacklistedVotes

packages/lib/shared/utils/numbers.spec.ts, packages/lib/shared/utils/numbers.ts
To avoid unnecessary wrapping where possible, let's remove decimal points for large numbers.
=> Remove decimal points for APRs above 1,000%

packages/lib/modules/pool/PoolDetail/PoolTypeTag.tsx
=> fix: in PoolTypeTag boosted case was missing TagWrapper

packages/lib/modules/eclp/hooks/EclpChartProvider.tsx, packages/lib/modules/eclp/hooks/useGetECLPLiquidityProfile.tsx, packages/lib/modules/pool/pool-tokens.utils.ts
fixes #995 
show rate adjusted underlying tokens instead of boosted (where applicable)
- for price
- and for display in legend
[example pool](https://beets.fi/pools/sonic/v3/0x7d836813d1d0b710979f2747c071eac8e8693198)
before:
after:
=> feat: use actionable tokens in eclp chart

packages/lib/modules/pool/actions/add-liquidity/useAddLiquidityStep.tsx, packages/lib/modules/transactions/transaction-steps/TransactionButton.tsx, packages/lib/modules/transactions/transaction-steps/lib.tsx, packages/lib/modules/transactions/transaction-steps/transaction.helper.ts, packages/lib/modules/transactions/transaction-steps/useTransactionSteps.tsx, packages/lib/modules/web3/contracts/useManagedErc20Transaction.ts, packages/lib/modules/web3/contracts/useManagedSendTransaction.ts, packages/lib/modules/web3/contracts/useManagedTransaction.ts
This is the first step of a big refactor to simplify the way we handle transaction (AKA `ManagedResult`) states.
=> refactor: addStep hook to use new transaction system

packages/lib/tsconfig.json
The old setup using: 
`"@repo/*": ["../*"]`
was causing issues when using auto imports in some IDEs as they added as valid imports:
`import {foo} from '/modules/bar'`
=> chore: change tsconfig.json relative paths

packages/e2e-tests/tests/dev/add-liquidity.spec.ts
Skip until permit2 signatures can be tested again.
The blocker is that all foundry default anvil accounts now have 7702 lists so, instead of using ECDSA.recover, the permit2 SignatureChecker lib will use 1271 signature verification first, breaking signature flow.
The foundry team confirmed that they will implement a feature to reset the default anvil when forking, so they do not have
7702 authorization lists by default. We have to skip this test until that feature is implemented.
From Foundry Support telegram:
=> chore: skip e2e test using permit2 signatures

packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/UserSnapshotValues.tsx, packages/lib/modules/pool/pool.utils.ts
`getTotalAprRaw` was using `getTotalAprLabel` to get the 'raw' apr by removing the percentage sign
however aprs > 1000% were also adding a comma to the `raw` apr, this breaks the potential weekly yield calc
the fix is for `getTotalAprRaw` to use  `getTotalApr` which returns the apr without a comma or percentage sign
=> fix: comma in apr label breaks weekly yield calc

apps/beets-frontend-v3/lib/modules/lst/hooks/useLstStakeStep.tsx, apps/beets-frontend-v3/lib/modules/lst/hooks/useLstUnstakeStep.tsx, apps/beets-frontend-v3/lib/modules/lst/hooks/useLstWithdrawStep.tsx
- remove `useMemo` (no longer needed here with React 19)
- also updated `useLstWithdrawStep` with the new txn state
=> fix: lst stake/unstake/withdraw

apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesStats/incentives-optimization/MyVotesStatsMyIncentivesOptimized.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesStats/incentives-optimization/useIncentivesOptimized.spec.ts, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesStats/incentives-optimization/useIncentivesOptimized.ts, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableRow.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/myVotes.helpers.ts, packages/lib/modules/web3/useTokenAllowances.integration.spec.ts, packages/lib/shared/utils/numbers.ts, packages/lib/test/utils/custom-renderers.tsx, packages/lib/test/utils/react-query.ts
- Some HH incentives have a token cap per vote that makes the incentive per vote not as high as `total_incentives / votes`.
- Changed the optimization step to 1% as Xeonus mentioned that smaller amounts (we were using 0.01%) can cause transaction problems.
=> Use token caps when calculating voting incentives

apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/actions/submit/useSubmitVotesSteps.tsx
The useMemo was not being updated on transaction state changes, so we removed the useMemo which is simpler and safer. 
**After fix:** 
https://github.com/user-attachments/assets/2b680656-e94e-43fc-aacf-76c44769d960
=> fix: remove useMemo to fix bug in multi chunk voting

apps/beets-frontend-v3/lib/modules/reliquary/hooks/useApproveRelayerRelicsStep.tsx, apps/frontend-v3/app/(app)/debug/remove-allowance/page.tsx, apps/frontend-v3/app/(app)/debug/revoke-relayer-approval/page.tsx, packages/lib/modules/relayer/useApproveRelayerStep.tsx, packages/lib/modules/staking/gauge/useMinterApprovalStep.tsx, packages/lib/modules/tokens/approvals/permit2/usePermit2ApprovalSteps.tsx, packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx, packages/lib/modules/transactions/transaction-steps/TransactionButton.tsx, packages/lib/modules/web3/contracts/useManagedErc20Transaction.integration.spec.ts, packages/lib/modules/web3/contracts/useManagedErc20Transaction.ts, packages/lib/modules/web3/contracts/useManagedSendTransaction.integration.spec.ts, packages/lib/modules/web3/contracts/useManagedSendTransaction.ts, packages/lib/modules/web3/contracts/useManagedTransaction.ts
Last transaction refactor before being able to remove `TransactionStateProvider`.
- Refactors the remaining step hooks to the new transaction system
- Makes `onTransactionChange` prop mandatory in the 3 core transaction hooks (managed, managedErc20 and managedSend)
- Removes useMemo in hooks iterating multiple steps to avoid useMemo dependency issues due to transaction state changes.
=> refactor: make onTransactionChange required

packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx, packages/lib/modules/transactions/transaction-steps/TransactionStateProvider.tsx, packages/lib/modules/transactions/transaction-steps/lib.tsx, packages/lib/modules/transactions/transaction-steps/useTransactionSteps.tsx
After the previous trasaction handling refactors, TransactionStateProvider was not needed anymore but I reused it to globally handle the "onSuccess" state by step txhash. This will prevent unnecessary refetch calls (that we were sometimes avoiding with useMemos and useCallbacks that will become now unnecessary).
=> refactor: move onSuccess tx handling to global provider

packages/lib/config/projects/beets.ts
- remove 'sonic gems' app nav link
=> fix: update app nav links for beets

packages/lib/modules/lbp/LbpFormProvider.tsx, packages/lib/modules/lbp/modal/LbpCreationModal.tsx, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/modules/lbp/steps/useCreateLbpStep.tsx, packages/lib/modules/transactions/transaction-steps/useTransactionSteps.tsx, packages/lib/shared/hooks/usePersistentForm.ts
Closes #1178 
- added reset logic to `usePersistedForm` to manage interaction btwn local storage and react hook form
- validate existence of form values before defining pool creation input to fix premature build call query
- make reset progress button also reset state for transaction steps
=> [LBP] patch:  form reset to initial values

packages/lib/modules/pool/pool-tokens.utils.ts
only use a rate provider in an eclp when the token is _boosted_
=> fix: use rate providers in eclps

packages/lib/modules/pool/PoolDetail/PoolInfo/Erc4626Info.tsx, packages/lib/modules/pool/PoolDetail/PoolInfo/PoolContracts.tsx, packages/lib/modules/pool/PoolDetail/PoolInfo/RateProviderInfo.tsx, packages/lib/modules/tokens/token.types.ts
- use data from `poolTokens` to show rate providers and tokenized vaults
before:
after:
=> fix: use poolTokens data here

packages/lib/modules/lbp/steps/SaleStructureStep.tsx
how to reproduce the issue:
1. choose collateral token
2. refresh ui
3. collateral token is set again to the first token from the network's collateral tokens array
=> [LBP] fix: use collateral token from persistent storage

packages/lib/modules/lbp/steps/ProjectInfoStep.tsx
x handle is optional in the api so making it optional in the ui too
=> [LBP] make x handle optional

apps/frontend-v3/README.md
Replaced the outdated link to the non-existent TESTING.md file with a correct link to the "Testing" section in the root README.md. This ensures users can easily find up-to-date testing instructions for the project.
=> Fix broken link to testing instructions in README

packages/lib/shared/hooks/useAprTooltip.ts
the chain `Optimism` is available on both the balancer and beets app
currently it is only showing the vebal staking boost apr on Optimism through the balancer app
this PR adds showing the extra apr through the beets app too
before:
after:
=> fix: show staking boost on beets app

packages/lib/shared/components/navs/MobileNav.tsx
fixes #1308
check if link is external instead of always opening links externally
=> fix: check if link is external

packages/lib/config/config.types.ts, packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts, packages/lib/shared/components/promos/PromoBanners.tsx
Introduce a new hover state on large screens and up on the promo tiles on the `/pools` page:
=> Hover states on promo tiles on Pools page

packages/lib/modules/eclp/hooks/useGetECLPLiquidityProfile.tsx
increase margin for eclp isInRange check
the margin needs a small increase so a pool will display it is out of or in range more accurate
=> fix: increase margin for eclps

packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/UserSnapshotValues.tsx
We were using staked balance to calculate the potential weekly yield, and pools where staking cannot be done showed $0.
=> Use total balance when calculating potential weekly yield

packages/lib/modules/eclp/hooks/useGetECLPLiquidityProfile.tsx
see [this pool](https://beets.fi/pools/sonic/v2/0x1be3de1d5b5aaf9076071228bc091f8f100f967e000200000000000000000115), range should be 2500-3500 in reverse
before:
after:
=> fix: remove rounding from tokenScalingFactor

packages/lib/modules/reclamm/ReclAmmChartProvider.tsx, packages/lib/shared/components/badges/ClpBadge.tsx, packages/lib/shared/components/icons/WandIcon.tsx
- Fix broken icon in Pool readjusting status
- Using themed colors for better consistency and display on light mode
- Slightly smaller triangles
- Various padding adjustments
=> reCLAMM chart: Improve text legibility and colors on light mode

packages/lib/config/projects/balancer.ts, packages/lib/shared/components/icons/promos/PromoReclammIcon.tsx, packages/lib/shared/components/promos/PromoBanners.tsx
- Update promo tiles on pools page
- Replace Balancer v3 is live with reCLAMMs promo
- Temporarily set the active index to start on the reCLAMM promo
- Ideally set it back to random in a couple of days
=> New reCLAMM promo banner

packages/lib/modules/eclp/components/EclpChart.tsx, packages/lib/modules/eclp/hooks/EclpChartProvider.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolChartsContainer.tsx, packages/lib/modules/reclamm/ReclAmmChart.tsx, packages/lib/modules/reclamm/ReclAmmChartProvider.tsx, packages/lib/shared/components/btns/ReversedToggleButton.tsx, packages/lib/shared/components/icons/WandIcon.tsx
This repositions the toggle button to the top. This keeps the layout cleaner and keeps all interactive chart components near the top. It also allows use to use more vertical space for the chart itself.
- Create a new token toggle button
- Position it besides the chart tabs ButtonGroup (where the time period selector is placed for Vol, TVL, Fees)
- Remove the labels positioned at the bottom within the chart providers
- Make the layout with toggle responsive and mobile friendly
reCLAMMs:
CLPs:
=> Reposition token toggle button in reCLAMM and ECLP charts

package.json, packages/e2e-tests/package.json, packages/eslint-config/package.json, pnpm-lock.yaml
- bump @typescript-eslint/parser to 8.37.0
- bump lint-staged to 16.1.2
- bump dotenv to 17.2.0
- bump @typescript-eslint/eslint-plugin to 8.37.0
=> chore: update packages

packages/lib/modules/portfolio/merkl/MerklAlert.tsx
=> fix: use project name in merkl rewards alert

packages/lib/modules/reclamm/ReclAmmChartProvider.tsx
for tokens with a rate provider reclamm uses the underlying to calculate all price values
however in the ui we want to show the rate for the LST token(s) so we need to scale back using the price rate
=> fix: scale back tokens with a rate provider in reclamms

packages/lib/modules/reclamm/ReclAmmChartProvider.tsx, packages/lib/shared/utils/numbers.ts
Fixes #1400 
By default, reclamm price chart shows pricing in underlying. However, if a token has a rate but is NOT an erc4626, we want to show the rate scaled pricing (i.e. `wstETH`)
**pool w/ erc4626:**
https://mono-frontend-v3-git-1400-reclamm-price-chart-balancer.vercel.app/pools/ethereum/v3/0x6cc9ef68864cd4c2af5a40ffb027c4b5428674a1
**pool w/o erc4626:**
https://mono-beets-v3-git-1400-reclamm-price-chart-beethovenx.vercel.app/pools/sonic/v3/0xbdc8ec2f249c37ce3a84177b9da6660b3659d60a
**pool w/ erc4626 where underlying also has rate ( combined rate provider ):**
- maybe fetch rate on chain for underlying token?
- the `priceRate` from API will be for the erc4626
- should we fetch on chain for token rates? ( API `priceRate` seems a bit stale )
=> Reclamm: fix price chart for pools w/ rate & w/o erc4626

apps/beets-frontend-v3/lib/modules/lst/hooks/useGetAmountDelegatedPerValidator.tsx
As a quick workaround to normalize delegations, we shall unstake from a defined set.
=> filter validator set for unstaking

apps/beets-frontend-v3/lib/modules/lst/LstProvidersLayout.tsx
As tokens are loaded in the background now, it is possible that the Beets stakes page tries to load before the tokens are available.
=> Wait for tokens to be loaded before checking that there are staking tokens

packages/lib/modules/pool/actions/add-liquidity/handlers/BoostedUnbalancedAddLiquidityV3.handler.integration.spec.ts, packages/lib/modules/pool/actions/remove-liquidity/useBptTokenApprovals.tsx, packages/lib/modules/pool/actions/remove-liquidity/useRemoveLiquiditySteps.tsx
Bug that didn't allow to remove liquidity if signatures where disabled in settings.
=> Allow gas BPT approvals when the wallet does not allow signatures

packages/lib/modules/pool/PoolDetail/PoolActivityChart/PoolActivityChart.tsx, packages/lib/modules/pool/PoolDetail/PoolActivityChart/usePoolActivityChart.tsx
Closes #48 
Pool https://balancer.fi/pools/ethereum/v3/0x57c23c58b1d8c3292c15becf07c62c5c52457a42 is an example where circles get cut off in the expanded and collapsed states.
=> [#48] add margin for worst case scenario on pool activity chart

packages/lib/modules/web3/safe.hooks.tsx, packages/lib/modules/web3/wallet-connect/createWalletConnectConnector.ts, packages/lib/shared/components/alerts/ContractWalletAlert.tsx, packages/lib/shared/components/alerts/SafeAppAlert.tsx
Closes #1434 
Also fixes a problem with the Wallet Connect modal that wasn't shown on top of the RainbowKit modal.
=> [#1434] change the Safe app link for HyperEVM to Den app

packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx, packages/lib/modules/tokens/TokenIconStack.tsx, packages/lib/modules/tokens/TokenStackPopover.tsx, packages/lib/shared/utils/array.ts
A non existent token appeared on the weekly incentives at pool detail page.
https://balancer.fi/pools/ethereum/v3/0x6c5972311191097d002e804a9bf97c96c54059ed
=> Avoid showing token icons when they are not available

packages/lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx
pools with an apr which has a range break the layout
before:
after:
=> fix: portfolio page with range aprs

packages/lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx
- show button w/ staking options popup on Beets on Optimism
- show 'regular' stake button on Balancer on networks where Aura is not deployed
=> fix: show staking popup for Optimism on Beets

packages/lib/modules/portfolio/PortfolioTable/PortfolioFiltersProvider.tsx
in the portfolio pools list any hook which pointed to the pool itself wasn't  yet removed
this caused the apr tooltip to split swap fees when that is not neccessary
this is now fixed
before:
after:
=> fix: apr tooltip for reclamm in portfolio

packages/lib/modules/portfolio/PortfolioClaim/useProtocolRewards.ts
remove the (unusable) boosted tokens from the protocol revenue rewards array
this saves quite some gas on mainnet
=> fix: remove unusable reward tokens

apps/frontend-v3/app/layout.tsx
- Attempts to fix the '500' error on Google that sometimes displays.
The appzi script tag could be interfering with Next.js SSR. The layout file was refactored migrate Fathom analytics to Next.js Script component and remove head tag.
=> Bug fix: 500 error on Google

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx, packages/lib/modules/pool/alerts/usePoolAlerts.tsx, packages/lib/modules/pool/pool.helpers.ts
for pools where at least one token has an external oracle as the rate provider add a warning on the:
- pool detail page
- add liquidity modal
[example pool](https://balancer.fi/pools/arbitrum/v3/0xa978cc348a0b5de8bd564a1d8fe437787fd12664)
note: some pools also get this warning from metadata (so there is a duplicate warning), that will be cleaned up after merging this PR
=> feat: add warning for external oracle rp

packages/lib/modules/pool/actions/create/constants.ts, packages/lib/modules/pool/actions/create/modal/SimilarPoolsModal.tsx, packages/lib/modules/pool/actions/create/modal/useCheckForSimilarPools.ts, packages/lib/modules/pool/actions/create/steps/details/PoolDetailsStep.tsx, packages/lib/modules/pool/actions/create/steps/tokens/ChoosePoolTokens.tsx, packages/lib/modules/pool/actions/create/types.ts, packages/lib/shared/components/icons/NetworkIcon.tsx
=> feat: similar pools warning during creation config

packages/lib/modules/pool/actions/create/steps/details/ReClammConfiguration.tsx, packages/lib/modules/pool/actions/create/steps/details/useReClammConfigurationOptions.tsx
make `custom` option a regular radio instead of a checkbox
before:
after:
=> fix: pool creator reclamm options

packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/shared/components/inputs/MultiSelect.tsx
Improvements when selecting networks in the Pool List filters:
- When a network is now selected, the network name is now also displayed
- This is helpful for the user, and also makes the UI not look broken. 
- Also applies labels when multiple networks are selected.
=> Improve MultiSelect Filter UX 

packages/lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/UserSnapshotValues.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolVersionTag.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTableRow.tsx, packages/lib/modules/tokens/TokenRow/TokenRow.tsx, packages/lib/shared/components/other/Stat.tsx, packages/lib/shared/components/tooltips/LabelWithTooltip.tsx, packages/lib/shared/components/tooltips/TooltipWithTouch.tsx, packages/lib/shared/components/tooltips/apr-tooltip/AuraAprTooltip.tsx, packages/lib/shared/pages/PoolsPage/PoolPageStats.tsx, packages/lib/shared/services/chakra/themes/base/components.ts
=> Various UI/UX improvements

apps/beets-frontend-v3/lib/modules/lst/LstProvidersLayout.tsx, apps/beets-frontend-v3/lib/modules/reliquary/ReliquaryProvidersLayout.tsx, apps/frontend-v3/app/(app)/debug/token-input/page.tsx, apps/frontend-v3/lib/vebal/lock/VebalLockActionsLayout.tsx, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/modules/swap/SwapForm.tsx, packages/lib/modules/tokens/TokenInput/TokenInput.tsx, packages/lib/shared/pages/PoolCreationPage.tsx
price impact is only shown in the token input on the swap form
this change decouples them so that in all other places where token input is used, the price impact provider is no longer required
=> fix: decouple pi from token input
