packages/lib/package.json, pnpm-lock.yaml
This will fix the adds/removes.
=> chore: update b-sdk in package/lib

package.json
=> chore: default pnpm run dev uses dev:bal

packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx, packages/lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx, packages/lib/shared/hooks/useAprTooltip.ts
- Add indentation into the popover to show the levels
- Minor copy updates for increased clarity
=> Improved clarity for yield popovers

packages/eslint-config/.eslintrc.js, packages/eslint-config/.prettierrc.json, packages/eslint-config/library.js, packages/eslint-config/next.js, packages/eslint-config/package.json, packages/eslint-config/react-internal.js, packages/lib/.eslintignore, packages/lib/.eslintrc.js, packages/prettier-config/.eslintrc.cjs, packages/prettier-config/.eslintrc.js, packages/prettier-config/.prettierrc.json, packages/prettier-config/index.js, packages/prettier-config/package.json, pnpm-lock.yaml
- fixed eslint rules not found
- configure & run prettier/eslint for both prettier & eslint configs
=> chore: fix eslint rules

turbo.json
Remove turbo warnings from PRs.
=> chore: Add env vars to turbo config

packages/lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx
=> fix: token row width

apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/swap/[[...txHash]]/page.tsx, packages/lib/modules/pool/actions/add-liquidity/AddLiquidityProvider.tsx, packages/lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx, packages/lib/modules/pool/pool.helpers.spec.ts, packages/lib/modules/pool/pool.helpers.ts, packages/lib/modules/swap/SwapForm.tsx, packages/lib/modules/swap/SwapLayout.tsx, packages/lib/modules/swap/SwapProvider.tsx, packages/lib/modules/swap/handlers/PoolSwap.handler.integration.spec.ts, packages/lib/modules/swap/handlers/PoolSwap.handler.ts, packages/lib/modules/swap/swap.helpers.ts, packages/lib/modules/tokens/token.helpers.ts, packages/lib/test/data/all-gql-tokens.fake.ts
Implements pool swaps for nested pools. 
Can be tested with this nested pool swap: 
https://mono-frontend-v3-git-feat-nestedpoolswaps-balancer.vercel.app/pools/ethereum/v2/0x08775ccb6674d6bdceb0797c364c2653ed84f3840002000000000000000004f0/swap
=> feat: nested pool swaps

apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/swap/[[...txHash]]/page.tsx, packages/lib/modules/pool/PoolDetail/PoolHeader/PoolAdvancedOptions.tsx, packages/lib/modules/swap/SwapProvider.tsx
Also blocks pool swaps when there's no token metadata.
=> fix: add pool chain to swap state when isPoolSwap

packages/lib/modules/pool/PoolList/PoolListFilters.tsx
=> fix: Mobile create pool

apps/beets-frontend-v3/package.json
forgot to add the scripts for beets too
=> chore: add theme typings to beets

packages/lib/modules/hooks/useHook.ts, packages/lib/modules/pool/PoolDetail/PoolHeader/PoolMetaBadges.tsx, packages/lib/modules/pool/PoolDetail/PoolInfo/PoolContracts.tsx, packages/lib/shared/components/icons/HookIcon.tsx, packages/lib/shared/services/api/pool.graphql
=> feat: Hooks on pool page

packages/lib/debug-helpers.ts, packages/lib/modules/pool/actions/LiquidityActionHelpers.integration.spec.ts, packages/lib/modules/pool/actions/LiquidityActionHelpers.spec.ts, packages/lib/modules/pool/actions/LiquidityActionHelpers.ts, packages/lib/modules/pool/pool.helpers.ts, packages/lib/test/msw/builders/gqlPoolElement.builders.ts
Fixes issue reported in discord: 
https://discord.com/channels/638460494168064021/1302200249690886224/1302200251163349084
**Before:** 
**After:**
https://github.com/user-attachments/assets/7cf33084-659d-4f95-89d2-b9dac5060689
=> fix: allPoolTokens for pools with nested bptTokens

apps/beets-frontend-v3/app/(marketing)/risks/page.tsx, apps/frontend-v3/app/(marketing)/risks/page.tsx, pnpm-lock.yaml, turbo.json
Also includes some minor updates to links that pointed to the old repo.
=> fix: Lockfile / checks

packages/lib/modules/erc4626/Erc4626MetadataProvider.tsx, packages/lib/modules/erc4626/getErc4626Metadata.ts, packages/lib/modules/pool/PoolDetail/PoolComposition.tsx, packages/lib/modules/pool/PoolDetail/PoolTypeTag.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx, packages/lib/modules/pool/pool.types.ts, packages/lib/shared/services/api/apollo-global-data.provider.tsx
- fetch & use erc4626 metadata
- add *Boosted* to `PoolFilters`
=> feat: add erc4626 metadata

packages/lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx, packages/lib/shared/hooks/_mocks_/aprTooltipDataMock.ts, packages/lib/shared/hooks/useAprTooltip.spec.tsx, packages/lib/shared/hooks/useAprTooltip.ts
This pr fixes max apr calc and fixes swap fee apr type to the proper one
=> fix: apr max calc

packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx, packages/lib/modules/pool/PoolProvider.tsx, packages/lib/modules/pool/pool.helpers.ts, packages/lib/modules/pool/queries/useOnchainUserPoolBalances.ts
fix React warning when rendering PoolDetail page for a pool with a user balance
=> chore: fix order of hooks

packages/lib/modules/pool/PoolDetail/PoolInfo/HookInfo.tsx, packages/lib/modules/pool/PoolDetail/PoolInfo/PoolRisks/usePoolRisks.ts
this pr fixes links to hook risks anchor
=> fix: hooks risks link

packages/lib/modules/pool/PoolList/PoolListTable/PoolVersionTag.tsx
this pr adds styles to v3 pool badge
=> feat: v3 badge style

packages/lib/modules/pool/actions/add-liquidity/modal/AddLiquidityModal.tsx, packages/lib/modules/pool/actions/remove-liquidity/modal/RemoveLiquidityModal.tsx, packages/lib/modules/swap/SwapProvider.tsx, packages/lib/modules/swap/modal/SwapModal.tsx, packages/lib/modules/transactions/transaction-steps/receipts/receipt-parsers.ts, packages/lib/modules/transactions/transaction-steps/receipts/receipt.hooks.integration.spec.ts, packages/lib/modules/transactions/transaction-steps/receipts/receipt.hooks.ts
=> fix: wNativeAsset logs for v3

packages/lib/modules/pool/PoolList/PoolListTable/PollListTableDetailsCell.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTableHeader.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTableRow.tsx
This pr changes portfolio type column to details one, like on pools list page
=> feat: add portfolio details column

packages/lib/shared/components/btns/button-group/ButtonGroup.tsx
=> fix: alignment & width of group buttons

apps/frontend-v3/app/(app)/testooors/layout.tsx, apps/frontend-v3/app/(app)/testooors/page.tsx, packages/lib/config/networks/gnosis.ts, packages/lib/config/networks/mainnet.ts, packages/lib/config/networks/sepolia.ts, packages/lib/modules/transactions/transaction-steps/receipts/receipt.hooks.integration.spec.ts, packages/lib/package.json, packages/lib/shared/components/navs/NavBar.tsx, pnpm-lock.yaml
Do not merge without new sepolia pools as that would block QA tests.
=> chore: bump sdk to 0.33.3

packages/lib/shared/components/errors/UnbalancedAddError.tsx, packages/lib/shared/components/errors/UnbalancedError.test.tsx
=> chore: improve error message when on unbalanced simulation error

packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx
This pr sets all protocol versions filter to cow and v2
=> feat: change protocol version filter logic

packages/lib/modules/pool/PoolList/PoolListTable/PoolListTable.tsx
this pr closes https://github.com/balancer/frontend-monorepo/issues/255
=> fix: pool list table column width

apps/frontend-v3/app/layout.tsx, packages/lib/shared/components/site/providers.tsx
moved to frontend v3 app, since not needed in beets
=> feat: move vebal lock provider

apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/swap/[[...txHash]]/page.tsx, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/swap/[[...txHash]]/page.tsx, packages/lib/config/networks/gnosis.ts, packages/lib/config/networks/mainnet.ts, packages/lib/modules/pool/pool.helpers.ts, packages/lib/modules/swap/SwapProvider.tsx, packages/lib/modules/swap/handlers/BaseDefaultSwap.handler.ts, packages/lib/modules/swap/queries/useSimulateSwapQuery.ts, packages/lib/modules/transactions/transaction-steps/useSignPermit2Step.tsx, packages/lib/modules/transactions/transaction-steps/useSignPermitStep.tsx, packages/lib/shared/hooks/useMakeVarPersisted.ts
- Fixes swap router setup. 
- Fixes issue when pool swap network does not match wallet network.
=> fix: pool swap when shouldChangeNetwork

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx
=> fix: input form alignment

packages/lib/modules/swap/SwapForm.tsx, packages/lib/modules/swap/queries/useSimulateSwapQuery.ts, packages/lib/modules/swap/swap.helpers.ts, packages/lib/shared/utils/error-filters.ts
=> fix: detect swap with too small amount

apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/layout.tsx, apps/beets-frontend-v3/app/(app)/portfolio/[chain]/page.tsx, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/layout.tsx, apps/frontend-v3/app/(app)/portfolio/[chain]/page.tsx, packages/lib/modules/pool/PoolDetail/PoolActivity/usePoolActivity.tsx, packages/lib/modules/pool/PoolDetail/PoolActivityChart/usePoolActivityChart.tsx, packages/lib/modules/pool/pool.utils.ts, packages/lib/modules/swap/SwapLayout.tsx, packages/lib/modules/swap/SwapProvider.tsx
Reverts balancer/frontend-monorepo#296
=> Revert "fix: improve chainSlug handling"

packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx
this pr removes back v3 pools on prod
=> [Launch] feat: undo excl v3 pools

packages/lib/modules/pool/PoolDetail/PoolComposition.tsx, packages/lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx
=> fix: token display for my liquidity

packages/lib/modules/pool/actions/PoolActionsPriceImpactDetails.tsx, packages/lib/modules/pool/pool.helpers.ts
=> fix: calculate new share of pool using future balance (#244)

packages/lib/modules/pool/PoolDetail/PoolComposition.tsx, packages/lib/modules/pool/PoolDetail/PoolHeader/PoolBreadcrumbs.tsx, packages/lib/modules/pool/PoolDetail/PoolTypeTag.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PollListTableDetailsCell.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx, packages/lib/modules/pool/metadata/PoolsMetadataProvider.tsx, packages/lib/modules/pool/metadata/usePoolMetadata.tsx, packages/lib/shared/services/api/apollo-global-data.provider.tsx
=> feat: Support pool names

packages/lib/shared/components/inputs/SearchInput.tsx
this pr fixes empty search input when there is query string
=> fix: lost search filter text

packages/lib/modules/swap/SwapProvider.tsx, packages/lib/modules/swap/useSwapSteps.tsx, packages/lib/modules/tokens/approvals/approval-rules.ts, packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx, packages/lib/modules/web3/useTokenAllowances.tsx
- Fixes initial selectedChain logic for Pool Swaps. 
- Avoids calling `allowance` `readContracts` query when  the params are not loaded.
=> fix: allowance query

apps/beets-frontend-v3/package.json, packages/lib/config/config.types.ts, packages/lib/config/networks/sonic.ts, packages/lib/modules/web3/contracts/useMulticall.ts, packages/lib/package.json, pnpm-lock.yaml
=> fix: multicall3 workaround

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, packages/lib/package.json, pnpm-lock.yaml
Fixes https://github.com/balancer/frontend-monorepo/security/dependabot/36
=> Next.js authorization bypass vulnerability

packages/lib/modules/pool/actions/add-liquidity/form/TokenInputs.tsx, packages/lib/modules/pool/pool.helpers.ts, packages/lib/modules/pool/pool.types.ts, packages/lib/modules/tokens/TokenInput/TokenInput.tsx, packages/lib/modules/tokens/token.helpers.ts, packages/lib/shared/services/api/pool-tokens.graphql
=> fix: Token inputs

packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx
Fixes:
https://discord.com/channels/638460494168064021/1320620411448197160/1320620414346727505
=> fix: swap symbol

packages/lib/modules/pool/alerts/pool-issues/PoolIssue.labels.tsx
Closes #397
Thanks @sergeypanin1994 for your PR. Addressing it here as yours got out of sync.
=> chore: update Twitter URL to x.com format

packages/lib/config/networks/mainnet.ts
=> chore: add  80BAL20WETH + WETH to disallowNestedActions

apps/frontend-v3/sentry.client.config.ts
Adds sentry tags for 'known_issues' to that we can filter and improve sentry reports.
=> feat: add sentry tags for known issues

packages/lib/shared/components/inputs/SearchInput.tsx
set focus to search input on load(/open)
=> fix: set focus to input

apps/beets-frontend-v3/lib/modules/lst/hooks/useGetAmountDelegatedPerValidator.tsx
unstake lst from validator with highest amount delegated
=> fix: lst unstake rule

packages/lib/modules/pool/pool.helpers.ts
see here: https://balancerecosystem.slack.com/archives/C02F9EMRKQA/p1737616883377069
=> fix: only check erc4626 for v3

apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/migrate-stake/page.tsx, apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/stake/page.tsx, apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/swap/[[...txHash]]/page.tsx, apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/unstake/page.tsx, apps/beets-frontend-v3/app/(app)/pools/not-found.tsx, apps/beets-frontend-v3/app/(app)/swap/[[...slug]]/page.tsx, apps/beets-frontend-v3/app/not-found.tsx, apps/beets-frontend-v3/app/sitemap.ts, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/migrate-stake/page.tsx, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/stake/page.tsx, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/swap/[[...txHash]]/page.tsx, apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/unstake/page.tsx, apps/frontend-v3/app/(app)/pools/not-found.tsx, apps/frontend-v3/app/not-found.tsx, packages/lib/shared/pages/MigrateStakePage.tsx, packages/lib/shared/pages/NotFoundPage.tsx, packages/lib/shared/pages/PoolSwapPage.tsx, packages/lib/shared/pages/StakePage.tsx, packages/lib/shared/pages/UnstakePage.tsx
- add more page wrappers
- add additional not found pages in /pools path
- fix pool page description for beets
- update sitemap for beets
=> chore: create more page wrappers

apps/beets-frontend-v3/lib/components/navs/NavBarContainer.tsx, apps/frontend-v3/lib/components/navs/NavBarContainer.tsx, packages/e2e-tests/tests/balancer/bal.add-liquidity.spec.ts, packages/lib/config/config.types.ts, packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts, packages/lib/modules/web3/ConnectWallet.tsx, packages/lib/shared/components/navs/NavBar.tsx
Adds option to create Coinbase wallet. Implements #34
=> feat: Add create wallet button

apps/frontend-v3/app/(app)/lbp/create/page.tsx
Scaffolding for LBP form layout.
=> feat: Add LBP form layout

packages/lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx, packages/lib/package.json, packages/lib/shared/utils/numbers.ts, pnpm-lock.yaml
=> fix: add custom function to disable removes with too small usd amounts

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, pnpm-lock.yaml
=> fix: theme typings error

packages/lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx
=> Centered the connect wallet button

packages/lib/config/config.types.ts, packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts, packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/modules/pool/PoolList/PoolListLayout.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx, packages/lib/modules/pool/pool.types.ts
=> feat: add pool hooks filter

packages/lib/modules/lbp/LbpForm.tsx, packages/lib/modules/lbp/LbpFormProvider.tsx, packages/lib/modules/lbp/steps/ProjectInfoStep.tsx, packages/lib/modules/lbp/steps/ReviewStep.tsx, packages/lib/modules/lbp/steps/SaleStructureStep.tsx
https://github.com/user-attachments/assets/c50341b7-f9f5-4e68-8ab7-c8d238682bb7
=> chore: Add step components and back button

packages/lib/modules/lbp/LbpForm.tsx, packages/lib/modules/lbp/LbpFormAction.tsx, packages/lib/modules/lbp/LbpFormProvider.tsx, packages/lib/modules/lbp/lbp.types.ts, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/shared/utils/addresses.ts
Uses react-hook-form to control form state. In this PR I propose a separate form state for each step that needs it (1 & 2). The useForm hook from react-hook-form is primarily used to control form validations and progression to next step.
https://github.com/user-attachments/assets/021f58f6-58da-4d1e-b495-aeaf659d7cb7
=> feat: Add LBP form state

packages/lib/modules/pool/PoolDetail/PoolComposition.tsx, packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx, packages/lib/modules/pool/useGetPoolTokensWithActualWeights.tsx, packages/lib/shared/components/alerts/BalAlertContent.tsx
plus a small style fix for `BalAlertContent`
=> chore: add hook to get pool weights

packages/lib/config/config.types.ts, packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts, packages/lib/shared/components/alerts/SafeAppAlert.tsx
_is_ on safe app list:
is _not_ on safe app list:
=> fix: show conditional text for safe app list

apps/frontend-v3/app/(marketing)/risks/page.tsx
Closes https://github.com/balancer/frontend-monorepo/pull/644
=> chore: add risks section for MEV hook

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx, packages/lib/shared/components/alerts/BalAlert.tsx, packages/lib/shared/components/icons/LightbulbIcon.tsx
=> fix: show info msg for proportional add

packages/lib/modules/pool/PoolList/PoolListTable/PoolListTable.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/modules/pool/PoolList/usePoolListQueryState.tsx, packages/lib/modules/pool/pool.types.ts, packages/lib/modules/pool/tags/PoolTagsProvider.tsx
the api added `'POINTS'` as tag for any pool with any points
this simplifies the pool filter and the points display on the list page
=> fix: points display on pool list & detail pages

apps/frontend-v3/app/(marketing)/3rd-party-services/page.tsx, apps/frontend-v3/app/(marketing)/cookies-policy/page.tsx, apps/frontend-v3/app/(marketing)/privacy-policy/page.tsx, apps/frontend-v3/app/(marketing)/risks/page.tsx, apps/frontend-v3/app/(marketing)/terms-of-use/page.tsx
Fixes #646 
Title blur is fixed for - 
- Terms of use
- Privacy policy
- Cookies policy
- 3rd party services
- Risks
Fix example for Risks
=> fix: title blur fixed

.gitignore, apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, package.json, packages/lib/package.json, pnpm-lock.yaml
=> chore: bump packages per dependabot suggestions

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, packages/lib/modules/price-impact/price-impact.utils.ts, packages/lib/package.json, packages/lib/test/integration/sdk-utils.ts, pnpm-lock.yaml
Closes https://github.com/balancer/frontend-monorepo/pull/703
=> fix: bump to sdk 2.3.1 to fix surge error handling

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx
=> Added warning for out of range CLP

packages/lib/package.json, pnpm-lock.yaml
- `@graphql-codegen/typescript-msw` is not used ->removed it
- update `react-hook-form`
- update `msw`
=> chore: update packages dependabot

packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx
=> fix: popup z index

packages/lib/modules/vebal/lock/form/VebalLockForm.tsx
=> [#789] add info about getting veBAL when no amout to be locked

packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/UserSnapshotValues.tsx, packages/lib/modules/pool/useGetPoolRewards.spec.tsx, packages/lib/modules/pool/useGetPoolRewards.tsx, packages/lib/modules/pool/useGetUserPoolRewards.spec.tsx, packages/lib/modules/pool/useGetUserPoolRewards.tsx, packages/lib/modules/tokens/TokenIcon.tsx, packages/lib/modules/tokens/TokenIconStack.tsx, packages/lib/modules/tokens/TokenRow/TokenRow.tsx, packages/lib/modules/tokens/TokenStackPopover.tsx
fixes #777 
note: the sorting changes are intentionally
=> feat: add token icon stack popover

packages/lib/shared/services/api/pool.graphql
=> fix: update gql files

apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, packages/lib/modules/pool/actions/add-liquidity/handlers/ProportionalAddLiquidityV3.handler.ts, packages/lib/modules/pool/actions/add-liquidity/handlers/UnbalancedAddLiquidityV3.handler.ts, packages/lib/modules/pool/actions/remove-liquidity/handlers/ProportionalRemoveLiquidityV3.handler.ts, packages/lib/modules/pool/actions/remove-liquidity/handlers/SingleTokenRemoveLiquidityV3.handler.ts, packages/lib/package.json, pnpm-lock.yaml
=> chore: bump to sdk 2.6.0

packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyIncentives.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/shared/GainBadge.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/actions/submit/modal/SubmitVotesPreview.tsx
=> [#792] add the potencial incentives to vote review screen

packages/lib/modules/vebal/lock/form/VebalLockForm.tsx, packages/lib/modules/vebal/vebal-chart/VebalLocksChart.tsx, packages/lib/modules/vebal/vebal-chart/useVebalLocksChart.tsx
=> [#788] show the max amount of vebal when locked for one year

packages/lib/modules/vebal/vote/VoteList/VoteListTable/VoteListTableRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/VoteWeightInput.tsx, packages/lib/modules/vebal/vote/Votes/VotesProvider.tsx
=> [#786] Add tooltips to disabled items

packages/lib/modules/vebal/VebalStats/UserVebalStatsValues.tsx, packages/lib/modules/vebal/VebalStats/VebalStatsLayout.tsx, packages/lib/modules/vebal/cross-chain/CrossChainBoost.tsx, packages/lib/modules/vebal/cross-chain/CrossChainSyncModal.tsx, packages/lib/modules/vebal/cross-chain/CrossChainSyncRow.tsx, packages/lib/modules/vebal/lock/form/VebalLockForm.tsx, packages/lib/modules/vebal/lock/steps/lock-steps.utils.ts, packages/lib/modules/vebal/useVebalUserData.ts, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableRow.tsx, packages/lib/modules/vebal/vote/Votes/VotesProvider.tsx, packages/lib/modules/vebal/vote/useVeBALBalance.integration.spec.ts, packages/lib/modules/vebal/vote/useVeBALBalance.ts, packages/lib/test/utils/wagmi/fork-default-balances.ts
=> [#785] get veBAL balance onchain instead of from API

packages/lib/modules/vebal/vote/VoteList/VoteListProvider.tsx, packages/lib/modules/vebal/vote/VoteList/VoteListTable/VoteListTable.tsx, packages/lib/modules/vebal/vote/VoteList/VoteListTable/VoteListTableRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, packages/lib/modules/vebal/vote/Votes/VotesContainer.tsx
=> [#447] fix expired pools filter on the vote list page

packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyVebal.tsx
=> [#844] add expired tag on My veBAL chip on voting page

apps/frontend-v3/lib/components/navs/NavBarContainer.tsx, packages/lib/modules/vebal/cross-chain/useCrossChainSyncSteps.tsx, packages/lib/modules/vebal/lock/steps/useLockStep.integration.spec.tsx, packages/lib/modules/vebal/lock/steps/useLockStep.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyIncentivesOptimized.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/useVeBALIncentives.integration.spec.ts, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/useVeBALIncentives.ts, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTable.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableHeader.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableSubmitRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableTotalRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/VoteExceededTooltip.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/VoteTimeLockedTooltip.tsx, packages/lib/modules/vebal/vote/Votes/VotesContainer.tsx, packages/lib/modules/vebal/vote/Votes/VotesProvider.tsx, packages/lib/modules/vebal/vote/vote.helpers.ts
Closes #791 
As the optimization algorithm is still missing, the button action has been removed and the text now says `Coming soon`.
Also used this issue to review all the fixme's and todo's in the vebal code (that is why so many files with small changes)
=> [#791] Remaining states of 'My incentives optimized' chip

apps/frontend-v3/app/(app)/vebal/manage/extend/page.tsx, packages/lib/modules/vebal/VebalManage.tsx, packages/lib/modules/vebal/lock/VebalExtend.tsx, packages/lib/modules/vebal/lock/form/VebalLockForm.tsx, packages/lib/modules/vebal/lock/form/VebalUnlockForm.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyVebal.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/shared/MyVebalChargeTooltip.tsx
=> [#851] Improve differentiation between Get veBAL and Extend lock modals

packages/lib/modules/pool/PoolList/PoolListPoolDisplay.tsx
show tokens instead of names for pools (only commented out for now)
=> feat: show pool tokens for Beets

packages/lib/config/config.types.ts, packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts, packages/lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkPools.tsx, packages/lib/modules/portfolio/merkl/merkl.types.ts, packages/lib/modules/portfolio/merkl/useHasMerklRewards.ts
=> feat: update merkl api to v4

packages/lib/modules/vebal/lock/form/VebalLockForm.tsx, packages/lib/modules/vebal/lock/form/WeeklyYieldTooltip.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/useVeBALIncentives.ts, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/useVeBALPool.ts
=> [#95] add potential weekly yield in lock form

packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx
=> [#845] show important warnings on its own on voting page

apps/beets-frontend-v3/lib/modules/lst/components/LstWithdraw.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx, packages/lib/shared/components/pagination/Pagination.tsx, packages/lib/shared/components/pagination/getPaginationProps.ts, packages/lib/shared/components/tables/PaginatedTable.tsx
=> [#840] go to first page when number of pages have changed

packages/lib/modules/vebal/lock/VebalLockProvider.tsx, packages/lib/modules/vebal/lock/form/VebalLockForm.tsx, packages/lib/modules/vebal/lock/form/WeeklyYieldTooltip.tsx
=> [#868] improve UI when locking additional veBAL

packages/lib/modules/web3/contracts/useManagedSendTransaction.ts
- for managed send txns increase the gas limit by 10%, this is mainly to make sure txns involving v3 boosted pools don't run out of gas
=> fix: always increase gas limit estimate by 10%

packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsAverageReward.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyIncentives.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyVebal.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesStats/shared/GainBadge.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableTotalRow.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/VoteExceededTooltip.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/VoteUnallocatedTooltip.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/VoteWeight.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/actions/submit/modal/SubmitVotesPreview.tsx, packages/lib/modules/vebal/vote/Votes/MyVotes/myVotes.helpers.ts, packages/lib/modules/vebal/vote/Votes/MyVotes/myVotes.types.ts, packages/lib/shared/utils/numbers.spec.ts, packages/lib/shared/utils/numbers.ts
Still some places doing calculations with numbers, but it is a start.
=> Use bigint and bignumber for calculations

packages/lib/config/projects/balancer.ts, packages/lib/config/projects/beets.ts
will unhide for balancer only in the quant-amm support PR
=> chore: hide btf pool type

packages/lib/modules/vebal/VeBalLockButtons.tsx, packages/lib/modules/vebal/VeBalPotentialBar.tsx, packages/lib/modules/vebal/VeBalSectionHeader.tsx, packages/lib/modules/vebal/VebalManage.tsx, packages/lib/modules/vebal/VebalStats/UserVebalStatsValues.tsx, packages/lib/modules/vebal/VebalStats/useVeBalUserStats.integration.spec.tsx, packages/lib/modules/vebal/VebalStats/useVeBalUserStats.ts, packages/lib/modules/vebal/__mocks__/provider-mocks.tsx, packages/lib/modules/vebal/lock/steps/useLockStep.integration.spec.tsx, packages/lib/modules/vebal/useMaxAmountOfVeBal.integration.spec.tsx, packages/lib/modules/vebal/useMaxAmountOfVeBal.ts, packages/lib/modules/vebal/vebal-chart/useVebalLocksChart.tsx, packages/lib/modules/web3/impersonation/TimeMocker.tsx, packages/lib/test/data/all-gql-tokens.fake.ts, packages/lib/test/integration/sdk-utils.ts
=> feat: My veBAL potential progress bar

packages/lib/modules/pool/actions/stake.helpers.ts
=> fix: revert change for getCanStake

apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/myVotes.helpers.ts, packages/lib/package.json, pnpm-lock.yaml
One was missed and the theme cannot be changed from light to dark.
Also fixed an error calculating voting rewards.
=> Update all next-theme versions

apps/frontend-v3/app/(marketing)/privacy-policy/page.tsx
=> Update privacy policy

apps/frontend-v3/lib/vebal/vote/VoteList/VoteListFilters.tsx, packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/shared/components/inputs/MultiSelect.tsx
https://github.com/user-attachments/assets/678ed143-afb4-40a2-8c8b-f6394adb8deb
=> Fix animation on list filters popovers

apps/frontend-v3/lib/vebal/lock/modal/VebalLockModal.tsx
=> [#940] Incorrect amount in the Unlock preview for expired locks

apps/frontend-v3/lib/vebal/lock/VebalExtend.tsx, apps/frontend-v3/lib/vebal/lock/VebalLock.tsx, apps/frontend-v3/lib/vebal/lock/form/VebalLockForm.tsx, apps/frontend-v3/lib/vebal/lock/form/VebalUnlockForm.tsx, apps/frontend-v3/lib/vebal/lock/steps/lock-steps.utils.ts
=> [#938] amount edit always on when user clicks Get veBAL button

apps/frontend-v3/app/(marketing)/risks/page.tsx
As written by Danko in https://github.com/balancer/frontend-monorepo/pull/935/files
New pull request to speed up the process as he does not have authorization to deploy on Vercel.
=> Update risk page

apps/frontend-v3/lib/vebal/vebal-chart/useVebalLocksChart.tsx
Closes #939 
@uiuxxx I don't think it is possible to have a tooltip that it is continuous (eChart seems to only show tooltips for data points) but I have added interpolated points where small density of data points (right now if there is more than 30 days between locks / data points a new interpolated data point will be added every 7 days to fill the void).
=> [#939] Change veBAL locks chart tooltip styles

apps/frontend-v3/lib/vebal/vote/VoteList/useVoteListFiltersState.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, packages/lib/modules/pool/PoolList/PoolListTokenPills.tsx
-  Make keys unique on StableTokenPills (caused an exception on the browser console)
- Sort Pool gauge vote list by Bribes/veBAL on load
- Calculate average reward without using HH data
=> More small fixes for veBAL

apps/frontend-v3/lib/vebal/VeBalCrossChainSync.tsx, apps/frontend-v3/lib/vebal/VeBalLockButtons.tsx, apps/frontend-v3/lib/vebal/VeBalPotentialBar.tsx, apps/frontend-v3/lib/vebal/VebalManage.tsx, apps/frontend-v3/lib/vebal/VebalStats/VebalStats.tsx, apps/frontend-v3/lib/vebal/vebal-chart/useVebalLocksChart.tsx, apps/frontend-v3/lib/vebal/vote/VoteList/VoteListLayout.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotes.tsx
- Improve padding in My Stats section
- Add new Sand ripple background to My Stats section
- Improve mobile layouts for Potential veBAL section
- Added new cross-chain sync placeholder section
=> Style improvements to Manage veBAL page

apps/frontend-v3/app/(app)/vebal/components/VebalBenefitsSection.tsx, apps/frontend-v3/app/(app)/vebal/components/VebalEcosystem.tsx, apps/frontend-v3/app/(app)/vebal/components/VebalFooterSection.tsx, apps/frontend-v3/app/(app)/vebal/components/VebalHeroSection.tsx, apps/frontend-v3/app/(app)/vebal/components/VebalHowSection.tsx, apps/frontend-v3/app/(app)/vebal/components/VebalStepCard.tsx
– Fixed mobile hero scroll bug (users had to scroll the whole length of the Sand ripples in the hero) before being able to scroll down the page
- Add scale up animation to the hero image on page load
- Minor UI improvements around padding, font sizes and shadows.
=> veBAL home page UI improvements

apps/frontend-v3/lib/vebal/VebalStats/UserVebalStatsValues.tsx, apps/frontend-v3/lib/vebal/lock/form/VebalLockForm.tsx, apps/frontend-v3/lib/vebal/lock/form/VebalUnlockForm.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotes.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTable.tsx, packages/lib/shared/services/chakra/themes/base/components.ts
1. My votes table improvements
- Better structuring for global vs vote table-specific alerts 
- The global alerts which affect both the Stats and Voting table are placed at the top
- The specific alerts related to the voting table remain in the same position but getting some extra top padding to clear the visual hierarchy and associate the alert with the voting table. 
- Better non-connected wallet state
- Show the empty state of the table  
2. Better alert layouts for those that extend wide on larger screens
-  New Alert variant that shouldn't affect existing Alerts, but now allow much better mobile layouts for Alerts with this new variant. Once incorporated, I can go through the site and assign this new variant to other alerts. 
3. Improved UI for expired veBAL unlock options
- Improved …
=> veBAL improvements with focus on My Votes section

packages/lib/modules/pool/PoolList/PoolListFilters.tsx, packages/lib/modules/pool/PoolList/PoolMinTvlFilter.tsx
=> feat: remap tvl values to slider

packages/lib/assets/css/global.css, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshot.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/UserSnapshotValues.tsx, packages/lib/shared/components/containers/FadeInOnView.tsx
=> feat: add swap vol to pool stats

apps/frontend-v3/lib/vebal/vebal-chart/useVebalLocksChart.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesProvider.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsAverageReward.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesStats/MyVotesStatsMyIncentives.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableRow.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotesTable/MyVotesTableTotalRow.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/incentivesBlacklist.ts, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/myVotes.helpers.ts, apps/frontend-v3/lib/vebal/vote/useVeBALBalance.ts, packages/lib/modules/vebal/vote/useGaugeVotes.tsx
Aura cannot receive incentives and their votes have to be subtracted from the total votes before calculating voting incentives.
=> Deal with users that cannot receive voting incentives

packages/lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkPools.tsx, packages/lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkPoolsLayoutWrapper.tsx
=> Added Sorting in Portfolio Claims

package.json, pnpm-lock.yaml
Bump turbo from 2.4.4 to 2.5.3.
=> chore: bump turbo

apps/frontend-v3/lib/vebal/vote/Votes/VotesIntroduction/VotingDeadline/VotingDeadlineCounter.tsx, apps/frontend-v3/lib/vebal/vote/Votes/VotesIntroduction/VotingDeadline/deadline.spec.ts, apps/frontend-v3/lib/vebal/vote/Votes/VotesIntroduction/VotingDeadline/deadline.ts, apps/frontend-v3/package.json
didn't work on timezones to the left of UTC
=> fix voting deadline calculation

apps/frontend-v3/README.md
=> chore: add deepwiki badge

packages/lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx
=> chore: add colored stars for merkl rewards

apps/frontend-v3/lib/vebal/VebalStats/UserVebalStatsValues.tsx
=> fix: hydration error vebal stats

packages/lib/modules/pool/PoolDetail/PoolCompositionChart.tsx
=> fix: increase height for quantamm

apps/frontend-v3/lib/vebal/vote/VoteList/SelectedPoolsMenu.tsx, apps/frontend-v3/lib/vebal/vote/Votes/MyVotes/MyVotes.tsx
=> [#1008] scroll to My Votes section when selecting voting pools

.github/workflows/checks.yml, apps/beets-frontend-v3/package.json, apps/frontend-v3/package.json, package.json, packages/e2e-tests/package.json, packages/e2e-tests/playwright.config.ts, packages/e2e-tests/tests/build/beets/beets.add-liquidity.spec.ts, packages/lib/package.json, packages/test/package.json, pnpm-lock.yaml
- bump @chakra-ui/cli to 2.5.8
- bump @types/node to 22.15.19
- bump require-in-the-middle to 7.5.2
- bump vitest to 3.1.3
=> chore: bump packages

apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/layout.tsx, apps/beets-frontend-v3/lib/modules/lzbeets-migrate/LzBeetsMigrate.tsx, packages/lib/shared/hooks/useUserBalance.tsx
=> fix: wagmiprovider error in beets app

packages/lib/shared/components/inputs/SliderWithSteps.tsx
=> [#1010] Add tooltip and disabled state to Lock duration Slider for locked parts

packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx
take out quantamm apr for those pools and put back swap fees apr for them
=> fix: take out quantamm apr for now

apps/beets-frontend-v3/next.config.ts
update redirects and fix headers
=> fix: update next config for beets

apps/frontend-v3/app/(app)/lbp/create/page.tsx, packages/lib/modules/lbp/header/FeatureLink.tsx, packages/lib/modules/lbp/header/HeaderBanner.tsx, packages/lib/modules/lbp/header/LearnMoreModal.tsx
=> [#1071] create header banner for LBP page

apps/frontend-v3/app/(app)/debug/modal/page.tsx, packages/lib/shared/components/animations/AnimateHeightChange.tsx
=> [#1082] remove space on modals between the body and the footer

apps/frontend-v3/lib/vebal/lock/modal/VebalLockModal.tsx, apps/frontend-v3/lib/vebal/lock/steps/useLockSteps.tsx
=> [#1081] remove approvals when extending lock for veBAL

packages/lib/modules/lbp/LbpForm.tsx, packages/lib/modules/lbp/LbpFormProvider.tsx, packages/lib/modules/lbp/LbpPreview.tsx, packages/lib/modules/lbp/lbp.types.ts, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/modules/lbp/steps/WeightAdjustmentTypeInput.tsx, packages/lib/shared/components/inputs/InputWithError.tsx
- Allow for custom weight adjustment
- Preview of token icon
- Get help button to open the learn more modal
- Button to paste the token address on the input
Still not 1:1 with the designs (missing some error management) but all the basic pieces and behaviour are there.
=> [#653] Sale structure form improvements

apps/frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/page.tsx, packages/lib/modules/pool/LbpDetail/LbpDetail.tsx, packages/lib/modules/pool/LbpDetail/LbpHeader.tsx, packages/lib/modules/pool/PoolContainer.tsx, packages/lib/modules/pool/PoolDetail/PoolActivity/PoolActivity.tsx, packages/lib/modules/pool/PoolDetail/PoolDetail.tsx, packages/lib/modules/pool/useUserPoolEvents.ts
fixes #1109 
fixes #1116 
all hardcoded values are intentional
=> [LBP] feat: detail page scaffolding

packages/lib/modules/lbp/LbpPreview.tsx, packages/lib/modules/lbp/steps/preview/PoolWeights.tsx, packages/lib/modules/lbp/steps/preview/ProjectedPrice.tsx, packages/lib/modules/lbp/steps/preview/TokenSummary.tsx, packages/lib/modules/lbp/steps/sale-structure/ProjectedPriceChart.tsx, packages/lib/modules/lbp/steps/sale-structure/WeightsChart.tsx, packages/lib/shared/utils/chart.helper.ts
=> [#655] LBP creation preview charts

packages/lib/config/projects/beets.ts
- add `Brand` to footer links for beets
=> fix: update footer links for beets

apps/beets-frontend-v3/lib/modules/lst/components/LstWithdraw.tsx
use S logo instead of stS logo
=> fix: use correct logo

packages/lib/modules/pool/LbpDetail/LbpDetail.tsx, packages/lib/modules/pool/LbpDetail/LbpHeader/LbpHeaderTimeInfo.tsx, packages/lib/modules/pool/LbpDetail/Top10Holdings.tsx, packages/lib/modules/pool/PoolDetail/PoolActivityTable/PoolActivityTableRow.tsx, packages/lib/modules/user/EnsOrAddress.tsx, packages/lib/shared/hooks/date.hooks.ts, packages/lib/shared/utils/time.ts
Closes #1150
Closes #1151 
- Header countdown
- Top 10 holders when LBP is finished
- No pool activity before the start of LBP
(*) The before state of the swap section (disabled fields and warning) still missing
=> Before and after states on LBP pool detail

apps/frontend-v3/lib/components/navs/NavBarContainer.tsx, packages/lib/config/projects/balancer.ts, packages/lib/shared/components/navs/NavBar.tsx, packages/lib/shared/components/navs/useNav.tsx
- move vebal link from shared to balancer config
- move lbp link from balancer to shared config
=> fix: move app and test links

packages/lib/modules/lbp/steps/sale-structure/ProjectedPriceChart.tsx, packages/lib/modules/lbp/steps/sale-structure/WeightsChart.tsx, packages/lib/modules/pool/LbpDetail/LbpDetail.tsx, packages/lib/modules/pool/LbpDetail/LbpPoolChartsContainer.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/LbpPriceChart.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolChartTabsProvider.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolCharts.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolChartsProvider.tsx, packages/lib/shared/services/api/pool.graphql, packages/lib/shared/utils/chart.helper.ts
Missing historical balances from the API in order to show the complete graph
=> [#1113] show projected prices chart on the LBP pool detail page

packages/lib/modules/lbp/LbpFormProvider.tsx, packages/lib/modules/lbp/lbp.types.ts, packages/lib/modules/lbp/steps/ProjectInfoStep.tsx, packages/lib/modules/lbp/steps/useCreateLbpStep.tsx
just hooking up the basics while we wait for radio button designs to close #1177
=> LBP creation: scaffold custom owner input

packages/lib/config/projects/balancer.ts
=> [#1184] allow filtering pool list by LBP pool type

packages/lib/modules/lbp/steps/useSendMetadataStep.tsx
=> patch: show send metadata error message

packages/lib/modules/pool/LbpDetail/LbpDetail.tsx, packages/lib/modules/pool/LbpDetail/MyPurchases.tsx, packages/lib/modules/pool/LbpDetail/MyTransactions.tsx
=> [#1118] My Purchases and My Transactions on LBP pool detail

packages/lib/modules/pool/LbpDetail/GetFundsWarning.tsx, packages/lib/modules/pool/LbpDetail/LbpDetail.tsx, packages/lib/modules/pool/LbpDetail/MyTransactions.tsx, packages/lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx, packages/lib/shared/components/alerts/BalAlertButtonLink.tsx, packages/lib/shared/services/api/pool.graphql
=> [#1231] Extract LBP funds once it is finished

packages/lib/modules/lbp/steps/ProjectInfoStep.tsx, packages/lib/modules/lbp/steps/preview/TokenSummary.tsx, packages/lib/shared/hooks/url.hooks.ts, packages/lib/shared/utils/query-errors.ts
=> [#1202] Check that the image URL for the the launch token exists

packages/lib/modules/lbp/LbpFormProvider.tsx, packages/lib/modules/lbp/lbp.types.ts, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/modules/lbp/steps/review/OtherSaleDetails.tsx, packages/lib/modules/lbp/steps/review/ReviewStep.tsx, packages/lib/modules/lbp/steps/useCreateLbpStep.tsx, packages/lib/shared/components/inputs/InputWithError.tsx
=> [#1279] Custom fee for LBPs

apps/frontend-v3/app/(app)/lbp/create/[[...txHash]]/layout.tsx, packages/lib/modules/lbp/LbpCreationProvider.tsx, packages/lib/modules/lbp/LbpFormAction.tsx, packages/lib/modules/lbp/modal/LbpCreationModal.tsx, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/modules/lbp/steps/review/ReviewStep.tsx, packages/lib/modules/lbp/steps/useCreateLbpStep.tsx, packages/lib/modules/lbp/steps/useCreateLbpSteps.tsx, packages/lib/modules/pool/actions/initialize/useInitializePoolBuildCall.ts, packages/lib/modules/tokens/approvals/useTokenApprovalSteps.tsx
Closes #1176 
lmk if u think we should change collateral token symbol/name for the modal summary to be the wrapped native asset
=> [LBP] init using native asset

packages/lib/modules/lbp/pool/lbp.helpers.ts, packages/lib/modules/lbp/pool/usePoolStats.ts, packages/lib/modules/lbp/pool/usePriceInfo.ts, packages/lib/modules/pool/LbpDetail/LbpHeader/LbpHeaderStats.tsx, packages/lib/modules/pool/LbpDetail/LbpPoolCharts/LbpPoolChartsProvider.tsx, packages/lib/modules/pool/LbpDetail/LbpPoolCharts/LbpPriceChart.tsx, packages/lib/modules/pool/PoolDetail/PoolCompositionChart.tsx, packages/lib/shared/services/api/lbp.graphql
=> [#1111] show stats on LBP pool detail header

apps/frontend-v3/app/(app)/lbp/create/[[...txHash]]/page.tsx, apps/frontend-v3/app/(app)/vebal/components/VebalBenefitsSection.tsx, apps/frontend-v3/lib/vebal/VeBalManagePromos.tsx, packages/lib/modules/lbp/LbpPreview.tsx, packages/lib/modules/lbp/header/FeatureLink.tsx, packages/lib/modules/lbp/header/HeaderBanner.tsx, packages/lib/modules/lbp/header/LearnMoreModal.tsx, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/shared/components/StoneIcon.tsx, packages/lib/shared/components/icons/lbp/LbpBenefitsChartIcon.tsx, packages/lib/shared/components/icons/lbp/LbpBenefitsLightningIcon.tsx, packages/lib/shared/components/icons/lbp/LbpBenefitsScalesIcon.tsx
- UI improvements to the LBP header
- Minor layout adjustments to the create LBP form
- New StoneIcon component
- Applying of StoneIcons to places it was previously used in the app (e.g. within the veBAL experience).
=> Create LBP Header

packages/lib/modules/pool/LbpDetail/LbpPoolListInfo.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableDetailsCell.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/shared/services/api/pools.graphql
=> [#1183] show LBP info on pool list rows

packages/lib/modules/eclp/hooks/EclpChartProvider.tsx, packages/lib/modules/reclamm/ReclAmmChartProvider.tsx, packages/lib/shared/utils/numbers.ts
- rename
- tweak number of decimals
before:
after:
=> fix: update number formatter

package.json, packages/lib/package.json, packages/test/package.json, pnpm-lock.yaml
- bump wagmi to 2.15.6
- bump happy-dom to 18.0.1
- bump vitest to 3.2.4
=> chore: update packages

packages/lib/modules/eclp/hooks/useGetECLPLiquidityProfile.tsx
the margin was increased in #1319 but it turns out the increase is a bit too much
so decreasing it again to halfway between current and previous values
=> fix: decrease eclp margin again

packages/lib/modules/lbp/LbpForm.tsx, packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/modules/pool/PoolDetail/PoolInfo/PoolAttributes/useFormattedPoolAttributes.tsx, packages/lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx, packages/lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityProportional.tsx, packages/lib/modules/pool/actions/remove-liquidity/modal/RemoveLiquiditySummary.tsx, packages/lib/modules/tokens/TokenRow/TokenRow.tsx, packages/lib/modules/tokens/TokenRow/TokenRowGroup.tsx, packages/lib/modules/tokens/TokensProvider.tsx, packages/lib/modules/tokens/useTotalUsdValue.ts
fixes #1328 add missing token info (when getting funds out)
fixes #1330 add scroll to top on step change
=> [LBP] several fixes

packages/lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx, packages/lib/modules/pool/pool.helpers.spec.ts, packages/lib/modules/pool/pool.helpers.ts
=> [#1344] disable add and remove liquidity from INVESTMENT / MANAGED pools

packages/lib/modules/pool/LbpDetail/MyPurchases.tsx, packages/lib/modules/pool/LbpDetail/MyTransactions.tsx, packages/lib/modules/pool/PoolProvider.tsx
sync height of my purchases to my transactions (with a maximum height)
=> [LBP] fix: heights of my purchases and transactions

apps/frontend-v3/package.json, packages/lib/package.json, pnpm-lock.yaml
=> Update bignumber.js lib to 9.3.1

packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx, packages/lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx, packages/lib/modules/swap/SwapForm.tsx, packages/lib/modules/web3/wallets/useContractWallet.integration.spec.ts, packages/lib/modules/web3/wallets/useContractWallet.ts, packages/lib/shared/components/alerts/ContractWalletAlert.tsx
=> [#1166] show info message when connected with smart contract wallet that is not recognized

packages/lib/modules/lbp/steps/ProjectInfoStep.tsx, packages/lib/shared/hooks/url.hooks.ts
=> [#1359] stop checking for image type on LBP icon

packages/lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolChartsContainer.tsx
=> Fix placement of time period selector on pool charts

apps/beets-frontend-v3/app/(marketing)/risks/page.tsx, apps/frontend-v3/app/(marketing)/risks/page.tsx
plus a smol update for balancer risks page
=> fix: beets risks page

packages/lib/modules/transactions/RecentTransactionsProvider.tsx, packages/lib/modules/transactions/transaction-steps/TransactionStepButton.tsx, packages/lib/modules/transactions/transaction-steps/safe/MultisigStatus.tsx, packages/lib/modules/transactions/transaction-steps/safe/TransactionBatchButton.tsx, packages/lib/modules/transactions/transaction-steps/safe/safe.helpers.ts, packages/lib/modules/web3/contracts/useOnTransactionSubmission.ts, packages/lib/shared/components/other/RecentTransactions.tsx
=> [#180] Track Safe transactions in Recent transactions

packages/lib/modules/lbp/LbpPreview.tsx, packages/lib/modules/lbp/steps/preview/TokenSummary.tsx
=> [#1376] show launch token balance on LBP creation preview

packages/lib/modules/lbp/steps/SaleStructureStep.tsx, packages/lib/shared/hooks/custom-effect-hooks.ts
=> [#1385] check if the start time of the LBP is in the past periodically

packages/lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx, packages/lib/modules/portfolio/PortfolioTable/PortfolioTableRow.tsx, packages/lib/modules/transactions/RecentTransactionsProvider.tsx
=> [#1401] avoid flashing on the portfolio pool list

packages/lib/modules/pool/PoolDetail/PoolComposition.tsx
=> Refactor boosted pool info alerts

packages/lib/modules/lbp/steps/preview/TokenSummary.tsx, packages/lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx, packages/lib/modules/pool/tags/PoolTagsProvider.tsx
=> [#1427] show tooltip with points info on pool list

packages/lib/modules/pool/PoolDetail/PoolComposition.tsx, packages/lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx, packages/lib/modules/pool/PoolDetail/PoolTotalLiquidityDisplay.tsx, packages/lib/modules/pool/PoolDetail/PoolTotalLiquidityValue.tsx, packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx, packages/lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx, packages/lib/modules/pool/alerts/usePoolAlerts.spec.tsx, packages/lib/modules/pool/alerts/usePoolAlerts.tsx, packages/lib/modules/pool/usePoolTokenPriceWarnings.ts, packages/lib/modules/tokens/TokenRow/TokenRow.tsx
Closes #1380
See pool without token price example:
https://mono-test-v3-git-no-price-warning-balancer.vercel.app//pools/hyperevm/v3/0x77d8854b8b555959e890c0d771086517e46a58f0
=> Warnings for no fiat token price

packages/lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityProportional.tsx
=> fix: only withdraw top level tokens in recovery mode

packages/lib/shared/components/alerts/ContractWalletAlert.tsx
=> [#1426] avoid console errors when showing smart wallet info message

packages/lib/modules/pool/alerts/usePoolAlerts.spec.tsx, packages/lib/modules/pool/usePoolTokenPriceWarnings.ts, packages/lib/modules/tokens/TokenRow/TokenRow.tsx
a few fixes for #1432
- create map with missing token prices and check that
- add some blank lines for readability
- add some guards to prevent `undefined` in text
- fix hydration errors
=> fix: no fiat price fixes

packages/lib/modules/chains/ChainSelect.tsx, packages/lib/modules/chains/NativeTokenBalance.tsx, packages/lib/shared/components/inputs/SelectInput.tsx
fixes #49
please note the network switch modal is from rainbowkit and can't be customized
=> feat: show native token balances

packages/lib/modules/lbp/steps/useInitializeLbpStep.tsx, packages/lib/modules/pool/actions/add-liquidity/useAddLiquidityStep.tsx, packages/lib/modules/pool/actions/remove-liquidity/useRemoveLiquidityStep.tsx, packages/lib/modules/transactions/RecentTransactionsProvider.tsx, packages/lib/modules/transactions/transaction-steps/safe/TransactionBatchButton.tsx
=> [#1307] avoid infinite render loops on batched transactions

packages/lib/shared/components/alerts/ContractWalletAlert.tsx
- improve UI
- improve messaging
From:
To:
=> Improve UI of unknown smart contract wallet messaging

packages/lib/modules/pool/actions/add-liquidity/useAddLiquiditySteps.tsx, packages/lib/modules/swap/SwapProvider.tsx, packages/lib/modules/swap/swap.types.ts, packages/lib/modules/swap/useSwapSteps.tsx, packages/lib/modules/tokens/approvals/permit2/usePermit2ApprovalSteps.tsx, packages/lib/modules/vebal/vote/vote.helpers.ts, packages/lib/shared/app/react-query.provider.tsx
=> [#1481] allow disabling signatures on swap

packages/lib/config/projects/beets.ts
=> chore: fix minor typo

apps/frontend-v3/app/(marketing)/risks/page.tsx
Fixed broken links
Added note about Polygon zkEVM
=> Broken links.tsx

packages/lib/modules/pool/PoolDetail/PoolWeightCharts/FeaturedPoolWeightChart.tsx, packages/lib/modules/pool/PoolDetail/PoolWeightCharts/PoolWeightChart.tsx, packages/lib/modules/pool/PoolDetail/PoolWeightCharts/PoolWeightChartLegend.tsx, packages/lib/modules/tokens/TokenIcon.tsx, packages/lib/styles/token-colors.ts
Closes #56 
The colors of the generated fallback token icons also match the new token color system.
=> [#56] Update chart token colors system

packages/lib/modules/reclamm/ReclAmmChartProvider.tsx
=> fix: reclamm pool labels

packages/lib/modules/pool/actions/LiquidityActionHelpers.ts, packages/lib/modules/pool/actions/add-liquidity/form/AddLiquidityFormTabs.tsx, packages/lib/modules/pool/pool.helpers.ts
also hide proportional msg when proportional add is disabled
follow up to this PR will be #1585
=> fix: disable proportional add for weighted v1

packages/lib/modules/pool/LbpDetail/LbpHeader/LbpHeaderStats.tsx, packages/lib/shared/components/other/AnimatedNumber.tsx, packages/lib/shared/pages/PoolsPage/PoolPageStats.tsx
use same currency in pool & lbp stats
before:
after:
=> fix: show chosen currency in stats

packages/lib/styles/token-colors.ts
- Added more token colors, including for all current Plasma tokens
=> Update token colors

packages/lib/modules/lbp/LbpPreview.tsx, packages/lib/modules/lbp/header/HeaderBanner.tsx, packages/lib/modules/lbp/header/LearnMoreModal.tsx, packages/lib/modules/lbp/modal/LbpLearnMoreModal.tsx, packages/lib/modules/pool/actions/create/preview/PreviewPoolCreation.tsx, packages/lib/shared/components/modals/LearnMoreModal.tsx
- we don't have design / content for pool creation help modal yet
- ~not sure best place to move `LearnMoreModal.tsx`~
=> Share learn more modal

apps/beets-frontend-v3/package.json, apps/cow-amm-frontend-v3/package.json, apps/frontend-v3/package.json, packages/lib/package.json, pnpm-lock.yaml
=> Update SDK to fix swap slippage parsing error

apps/frontend-v3/app/(marketing)/layout.tsx, apps/frontend-v3/app/layout.tsx
- Improve description in metadata on home page & pools list page
=> Update metadata and OpenGraph tags

packages/lib/modules/pool/actions/add-liquidity/useAddLiquiditySteps.tsx, packages/lib/modules/pool/actions/claim/useClaimAllRewardsSteps.tsx, packages/lib/modules/pool/actions/remove-liquidity/useRemoveLiquiditySteps.tsx, packages/lib/modules/pool/actions/unstake/useClaimAndUnstakeStep.tsx, packages/lib/modules/relayer/signRelayerApproval.hooks.tsx, packages/lib/modules/relayer/useApproveRelayerStep.tsx, packages/lib/modules/relayer/useHasApprovedRelayer.ts, packages/lib/modules/swap/useSwapSteps.tsx
=> check if relayer approval is needed
